// ciencia-datos.js
// Datos agrupados por MECÁNICA DE JUEGO para un rendimiento perfecto.

const BANCO_CIENCIAS = {
    
"clasificar": [
    // === 1. ANIMALES (15 retos) ===
    { p: "¿Dónde viven los animales?", items: [{n:"Delfín",q:"dolphin",c:1,e:"🐬"},{n:"León",q:"lion",c:2,e:"🦁"},{n:"Tiburón",q:"shark",c:1,e:"🦈"},{n:"Cebra",q:"zebra",c:2,e:"🦓"},{n:"Águila",q:"eagle",c:3,e:"🦅"}], destinos: [{id:1,n:"Agua",e:"🌊"},{id:2,n:"Tierra",e:"🌳"},{id:3,n:"Aire",e:"☁️"}] },
    { p: "¿Qué comen?", items: [{n:"Vaca",q:"cow",c:1,e:"🐄"},{n:"Lobo",q:"wolf",c:2,e:"🐺"},{n:"Oveja",q:"sheep",c:1,e:"🐑"},{n:"Tigre",q:"tiger",c:2,e:"🐯"},{n:"Caballo",q:"horse",c:1,e:"🐎"}], destinos: [{id:1,n:"Plantas",e:"🌿"},{id:2,n:"Carne",e:"🥩"}] },
    { p: "¿Pelo, Plumas o Escamas?", items: [{n:"Perro",q:"dog",c:1,e:"🐶"},{n:"Loro",q:"parrot",c:2,e:"🦜"},{n:"Serpiente",q:"snake",c:3,e:"🐍"},{n:"Gato",q:"cat",c:1,e:"🐱"},{n:"Pez",q:"fish",c:3,e:"🐟"}], destinos: [{id:1,n:"Pelo",e:"🐕"},{id:2,n:"Plumas",e:"🪶"},{id:3,n:"Escamas",e:"🦎"}] },
    { p: "¿Nacen de Huevo o de Mamá?", items: [{n:"Gallina",q:"hen",c:1,e:"🐔"},{n:"Vaca",q:"cow",c:2,e:"🐮"},{n:"Tortuga",q:"turtle",c:1,e:"🐢"},{n:"Gato",q:"cat",c:2,e:"🐱"}], destinos: [{id:1,n:"Huevo",e:"🥚"},{id:2,n:"Mamá",e:"🤱"}] },
    { p: "¿Doméstico o Salvaje?", items: [{n:"Hámster",q:"hamster",c:1,e:"🐹"},{n:"Tigre",q:"tiger",c:2,e:"🐯"},{n:"Oveja",q:"sheep",c:1,e:"🐑"},{n:"León",q:"lion",c:2,e:"🦁"}], destinos: [{id:1,n:"En Casa/Granja",e:"🏠"},{id:2,n:"En la Selva",e:"🌴"}] },
    { p: "¿Tienen huesos?", items: [{n:"Perro",q:"dog",c:1,e:"🐶"},{n:"Gusano",q:"worm",c:2,e:"🪱"},{n:"Pez",q:"fish",c:1,e:"🐟"},{n:"Mariposa",q:"butterfly",c:2,e:"🦋"}], destinos: [{id:1,n:"Vertebrado",e:"🦴"},{id:2,n:"Invertebrado",e:"🐜"}] },
    { p: "¿Cómo se mueven?", items: [{n:"Canguro",q:"kangaroo",c:1,e:"🦘"},{n:"Serpiente",q:"snake",c:2,e:"🐍"},{n:"Rana",q:"frog",c:1,e:"🐸"},{n:"Caracol",q:"snail",c:2,e:"🐌"}], destinos: [{id:1,n:"Saltan",e:"⬆️"},{id:2,n:"Reptan",e:"〰️"}] },
    { p: "¿Día o Noche?", items: [{n:"Ardilla",q:"squirrel",c:1,e:"🐿️"},{n:"Murciélago",q:"bat",c:2,e:"🦇"},{n:"Mariposa",q:"butterfly",c:1,e:"🦋"},{n:"Búho",q:"owl",c:2,e:"🦉"}], destinos: [{id:1,n:"Día",e:"☀️"},{id:2,n:"Noche",e:"🌙"}] },
    { p: "¿Cuántas patas tienen?", items: [{n:"Pájaro",q:"bird",c:1,e:"🐦"},{n:"Perro",q:"dog",c:2,e:"🐶"},{n:"Pato",q:"duck",c:1,e:"🦆"},{n:"Araña",q:"spider",c:3,e:"🕷️"}], destinos: [{id:1,n:"2 patas",e:"✌️"},{id:2,n:"4 patas",e:"🍀"},{id:3,n:"Más patas",e:"🕷️"}] },
    { p: "¿Son Mamíferos o Aves?", items: [{n:"Ballena",q:"whale",c:1,e:"🐳"},{n:"Águila",q:"eagle",c:2,e:"🦅"},{n:"Humano",q:"baby",c:1,e:"👶"},{n:"Pingüino",q:"penguin",c:2,e:"🐧"}], destinos: [{id:1,n:"Mamífero",e:"🥛"},{id:2,n:"Ave",e:"🪶"}] },
    { p: "Animales de África o Granja", items: [{n:"Cebra",q:"zebra",c:1,e:"🦓"},{n:"Cerdo",q:"pig",c:2,e:"🐷"},{n:"Jirafa",q:"giraffe",c:1,e:"🦒"},{n:"Gallo",q:"rooster",c:2,e:"🐓"}], destinos: [{id:1,n:"Sabana",e:"🏜️"},{id:2,n:"Granja",e:"🚜"}] },
    { p: "¿Peligroso o Amistoso?", items: [{n:"Cocodrilo",q:"crocodile",c:1,e:"🐊"},{n:"Conejo",q:"rabbit",c:2,e:"🐰"},{n:"Tiburón",q:"shark",c:1,e:"🦈"},{n:"Oveja",q:"sheep",c:2,e:"🐑"}], destinos: [{id:1,n:"Peligro",e:"⚠️"},{id:2,n:"Amigo",e:"❤️"}] },
    { p: "¿Viven en el frío o calor?", items: [{n:"Oso Polar",q:"polar-bear",c:1,e:"🐻‍❄️"},{n:"Camello",q:"camel",c:2,e:"🐪"},{n:"Pingüino",q:"penguin",c:1,e:"🐧"},{n:"Escorpión",q:"scorpion",c:2,e:"🦂"}], destinos: [{id:1,n:"Hielo/Nieve",e:"❄️"},{id:2,n:"Desierto/Calor",e:"🔥"}] },
    { p: "¿Quién es muy lento?", items: [{n:"Tortuga",q:"turtle",c:1,e:"🐢"},{n:"Guepardo",q:"cheetah",c:2,e:"🐆"},{n:"Caracol",q:"snail",c:1,e:"🐌"},{n:"Caballo",q:"horse",c:2,e:"🐎"}], destinos: [{id:1,n:"Lento",e:"🐢"},{id:2,n:"Rápido",e:"⚡"}] },
    { p: "¿Tienen cuernos?", items: [{n:"Toro",q:"bull",c:1,e:"🐂"},{n:"Perro",q:"dog",c:2,e:"🐶"},{n:"Rinoceronte",q:"rhino",c:1,e:"🦏"},{n:"Gato",q:"cat",c:2,e:"🐱"}], destinos: [{id:1,n:"Tienen cuernos",e:"🤘"},{id:2,n:"No tienen",e:"❌"}] },

    // === 2. ESPACIO (15 retos) ===
    { p: "¿Tierra o Espacio Exterior?", items: [{n:"Planeta",q:"planet",c:1,e:"🪐"},{n:"Océano",q:"ocean",c:2,e:"🌊"},{n:"Cometa",q:"comet",c:1,e:"☄️"},{n:"Montaña",q:"mountain",c:2,e:"⛰️"}], destinos: [{id:1,n:"Espacio",e:"🚀"},{id:2,n:"Tierra",e:"🌍"}] },
    { p: "¿Cuerpo celeste o invento humano?", items: [{n:"Satélite",q:"satellite",c:2,e:"🛰️"},{n:"Sol",q:"sun",c:1,e:"☀️"},{n:"Cohete",q:"rocket",c:2,e:"🚀"},{n:"Luna",q:"moon",c:1,e:"🌙"},{n:"Telescopio",q:"telescope",c:2,e:"🔭"}], destinos: [{id:1,n:"Naturaleza",e:"✨"},{id:2,n:"Humano",e:"🛠️"}] },
    { p: "¿Se ve de Día o de Noche?", items: [{n:"Sol",q:"sun",c:1,e:"☀️"},{n:"Luna",q:"moon",c:2,e:"🌙"},{n:"Arcoiris",q:"rainbow",c:1,e:"🌈"},{n:"Estrellas",q:"star",c:2,e:"✨"}], destinos: [{id:1,n:"Día",e:"🏙️"},{id:2,n:"Noche",e:"🌃"}] },
    { p: "¿Planeta o Estrella?", items: [{n:"Tierra",q:"earth",c:1,e:"🌍"},{n:"Sol",q:"sun",c:2,e:"☀️"},{n:"Marte",q:"mars",c:1,e:"🔴"},{n:"Sirio",q:"star",c:2,e:"✨"}], destinos: [{id:1,n:"Planeta",e:"🪐"},{id:2,n:"Estrella",e:"⭐"}] },
    { p: "¿Qué flota en el espacio?", items: [{n:"Astronauta",q:"astronaut",c:1,e:"👨‍🚀"},{n:"Coche",q:"car",c:2,e:"🚗"},{n:"Nave",q:"space-shuttle",c:1,e:"🛸"},{n:"Árbol",q:"tree",c:2,e:"🌳"}], destinos: [{id:1,n:"Flota",e:"🌌"},{id:2,n:"Se cae",e:"🍎"}] },
    { p: "¿Rocoso o de Gas?", items: [{n:"Tierra",q:"ground",c:1,e:"🌍"},{n:"Júpiter",q:"jupiter",c:2,e:"🌬️"},{n:"Marte",q:"mars",c:1,e:"🔴"},{n:"Saturno",q:"saturn",c:2,e:"🪐"}], destinos: [{id:1,n:"Suelo duro",e:"🪨"},{id:2,n:"Todo gas",e:"☁️"}] },
    { p: "¿Qué usa un astronauta?", items: [{n:"Casco",q:"helmet",c:1,e:"🪖"},{n:"Bañador",q:"swimsuit",c:2,e:"🩱"},{n:"Botas",q:"boots",c:1,e:"🥾"},{n:"Gafas sol",q:"sunglasses",c:2,e:"🕶️"}], destinos: [{id:1,n:"Equipo",e:"👨‍🚀"},{id:2,n:"Ropa normal",e:"👕"}] },
    { p: "¿Es redondo?", items: [{n:"Luna",q:"full-moon",c:1,e:"🌕"},{n:"Cohete",q:"rocket",c:2,e:"🚀"},{n:"Planeta",q:"planet",c:1,e:"🪐"},{n:"Estrella fugaz",q:"shooting-star",c:2,e:"🌠"}], destinos: [{id:1,n:"Esfera",e:"⚽"},{id:2,n:"Alargado",e:"📐"}] },
    { p: "¿Da Luz o es Oscuro?", items: [{n:"Sol",q:"sun",c:1,e:"☀️"},{n:"Asteroide",q:"asteroid",c:2,e:"🪨"},{n:"Estrella",q:"star",c:1,e:"✨"},{id:2,n:"Espacio vacío",e:"🌌"}], destinos: [{id:1,n:"Brilla",e:"💡"},{id:2,n:"Oscuridad",e:"🌑"}] },
    { p: "¿Cerca o Lejos de nosotros?", items: [{n:"Nube",q:"cloud",c:1,e:"☁️"},{n:"Saturno",q:"saturn",c:2,e:"🪐"},{n:"Avión",q:"airplane",c:1,e:"✈️"},{n:"Galaxia",q:"galaxy",c:2,e:"🌌"}], destinos: [{id:1,n:"Cerca",e:"🏙️"},{id:2,n:"Muy Lejos",e:"🔭"}] },
    { p: "¿Son planetas del sistema solar?", items: [{n:"Marte",q:"mars",c:1,e:"🔴"},{n:"La Luna",q:"moon",c:2,e:"🌙"},{n:"Júpiter",q:"jupiter",c:1,e:"🪐"},{n:"El Sol",q:"sun",c:2,e:"☀️"}], destinos: [{id:1,n:"Planetas",e:"🪐"},{id:2,n:"Otros astros",e:"✨"}] },
    { p: "¿Hace calor o frío?", items: [{n:"Sol",q:"sun-fire",c:1,e:"☀️"},{n:"Urano",q:"ice-planet",c:2,e:"🧊"},{n:"Mercurio",q:"mercury",c:1,e:"🥵"},{n:"Neptuno",q:"neptune",c:2,e:"❄️"}], destinos: [{id:1,n:"Mucho Calor",e:"🥵"},{id:2,n:"Mucho Frío",e:"🥶"}] },
    { p: "¿Instrumento de ciencia?", items: [{n:"Telescopio",q:"telescope",c:1,e:"🔭"},{n:"Microscopio",q:"microscope",c:2,e:"🔬"},{n:"Sonda",q:"probe",c:1,e:"🛰️"},{n:"Lupa",q:"magnifying",c:2,e:"🔍"}], destinos: [{id:1,n:"Ver el espacio",e:"🔭"},{id:2,n:"Ver cosas diminutas",e:"🐜"}] },
    { p: "¿Realidad o Fantasía?", items: [{n:"Astronauta",q:"astronaut",c:1,e:"👨‍🚀"},{n:"Marciano verde",q:"alien",c:2,e:"👽"},{n:"Cohete",q:"rocket",c:1,e:"🚀"},{n:"Nave con ojos",q:"ufo",c:2,e:"🛸"}], destinos: [{id:1,n:"Cosas reales",e:"✅"},{id:2,n:"Cosas de cuentos",e:"✨"}] },
    { p: "¿Color del planeta?", items: [{n:"Marte",q:"mars",c:1,e:"🔴"},{n:"Tierra",q:"earth",c:2,e:"🌍"},{n:"Sol",q:"sun",c:3,e:"☀️"}], destinos: [{id:1,n:"Rojo",e:"🟥"},{id:2,n:"Azul/Verde",e:"🟦"},{id:3,n:"Amarillo",e:"🟨"}] },

    // === 3. CUERPO (15 retos) ===
    { p: "¿Parte externa o interna?", items: [{n:"Mano",q:"hand",c:2,e:"✋"},{n:"Corazón",q:"heart",c:1,e:"❤️"},{n:"Pie",q:"foot",c:2,e:"🦶"},{n:"Cerebro",q:"brain",c:1,e:"🧠"},{n:"Pulmón",q:"lung",c:1,e:"🫁"}], destinos: [{id:1,n:"Dentro (Órgano)",e:"🦴"},{id:2,n:"Fuera (Se ve)",e:"👀"}] },
    { p: "¿Qué es SALUDABLE?", items: [{n:"Comer fruta",q:"apple",c:1,e:"🍎"},{n:"Dormir poco",q:"tired",c:2,e:"😩"},{n:"Hacer deporte",q:"sport",c:1,e:"🏃"},{n:"Comer muchos dulces",q:"candy",c:2,e:"🍭"}], destinos: [{id:1,n:"Es Sano",e:"✅"},{id:2,n:"Es Malo",e:"❌"}] },
    { p: "¿Duro (Hueso) o Blando (Músculo)?", items: [{n:"Cráneo",q:"skull",c:1,e:"💀"},{n:"Lengua",q:"tongue",c:2,e:"👅"},{n:"Costilla",q:"ribs",c:1,e:"🦴"},{n:"Moflete",q:"cheek",c:2,e:"😊"}], destinos: [{id:1,n:"Duro",e:"💪"},{id:2,n:"Blando",e:"🧸"}] },
    { p: "¿Qué parte es de la CARA?", items: [{n:"Ojo",q:"eye",c:1,e:"👁️"},{n:"Rodilla",q:"knee",c:2,e:"🦵"},{n:"Nariz",q:"nose",c:1,e:"👃"},{n:"Tobillo",q:"ankle",c:2,e:"👣"}], destinos: [{id:1,n:"En la Cara",e:"😊"},{id:2,n:"En las Piernas",e:"🦵"}] },
    { p: "¿Higiene o Juego?", items: [{n:"Jabón",q:"soap",c:1,e:"🧼"},{n:"Peluche",q:"teddy",c:2,e:"🧸"},{n:"Cepillo dientes",q:"toothbrush",c:1,e:"🪥"},{n:"Balón",q:"ball",c:2,e:"⚽"}], destinos: [{id:1,n:"Para Limpiar",e:"✨"},{id:2,n:"Para Jugar",e:"🎨"}] },
    { p: "¿Cuántos tenemos?", items: [{n:"Boca",e:"👄",c:1},{n:"Ojos",e:"👀",c:2},{n:"Nariz",e:"👃",c:1},{n:"Manos",e:"🙌",c:2}], destinos: [{id:1,n:"Solo 1",e:"1️⃣"},{id:2,n:"Tenemos 2",e:"2️⃣"}] },
    { p: "¿Qué sentido usamos?", items: [{n:"Música",q:"music",c:1,e:"🎵"},{n:"Pintura",q:"paint",c:2,e:"🎨"},{n:"Campana",q:"bell",c:1,e:"🔔"},{n:"Arcoiris",q:"rainbow",c:2,e:"🌈"}], destinos: [{id:1,n:"Oído",e:"👂"},{id:2,n:"Vista",e:"👀"}] },
    { p: "¿Huele bien o huele mal?", items: [{n:"Flor",q:"flower",c:1,e:"🌸"},{n:"Basura",q:"trash",c:2,e:"🤢"},{n:"Perfume",q:"perfume",c:1,e:"👃"},{n:"Calcetín sucio",q:"sock",c:2,e:"🧦"}], destinos: [{id:1,n:"Rico",e:"😊"},{id:2,n:"Fuchi",e:"🤢"}] },
    { p: "¿Para qué sirve el órgano?", items: [{n:"Cerebro",q:"brain",c:1,e:"🧠"},{n:"Corazón",q:"heart",c:2,e:"❤️"},{n:"Pensar",q:"idea",c:1,e:"💡"},{n:"Sangre",q:"blood",c:2,e:"🩸"}], destinos: [{id:1,n:"Pensar",e:"💡"},{id:2,n:"Latir",e:"💓"}] },
    { p: "¿Qué nos ayuda a movernos?", items: [{n:"Hueso",q:"bone",c:1,e:"🦴"},{n:"Músculo",q:"muscle",c:1,e:"💪"},{n:"Camiseta",q:"shirt",c:2,e:"👕"},{n:"Zapato",q:"shoe",c:2,e:"👟"}], destinos: [{id:1,n:"Nuestro cuerpo",e:"🧍"},{id:2,n:"Nuestra ropa",e:"👕"}] },
    { p: "¿Dulce o Salado?", items: [{n:"Azúcar",q:"sugar",c:1,e:"🧂"},{n:"Sal",q:"salt",c:2,e:"🧂"},{n:"Pastel",q:"cake",c:1,e:"🍰"},{n:"Patatas fritas",q:"chips",c:2,e:"🍟"}], destinos: [{id:1,n:"Dulce",e:"🍭"},{id:2,n:"Salado",e:"🥨"}] },
    { p: "¿Frío o Caliente? (Tacto)", items: [{n:"Hielo",q:"ice",c:1,e:"🧊"},{n:"Sopa",q:"soup",c:2,e:"🥣"},{n:"Nieve",q:"snow",c:1,e:"❄️"},{n:"Fuego",q:"fire",c:2,e:"🔥"}], destinos: [{id:1,n:"Frío",e:"🥶"},{id:2,n:"Caliente",e:"🥵"}] },
    { p: "¿Parte del brazo o la pierna?", items: [{n:"Codo",q:"elbow",c:1,e:"💪"},{n:"Rodilla",q:"knee",c:2,e:"🦵"},{n:"Hombro",q:"shoulder",c:1,e:"👕"},{n:"Tobillo",q:"ankle",c:2,e:"👣"}], destinos: [{id:1,n:"Brazo",e:"💪"},{id:2,n:"Pierna",e:"🦵"}] },
    { p: "¿Qué crece en nuestro cuerpo?", items: [{n:"Pelo",q:"hair",c:1,e:"💇"},{n:"Uñas",q:"nails",c:1,e:"💅"},{n:"Reloj",q:"watch",c:2,e:"⌚"},{n:"Anillo",q:"ring",c:2,e:"💍"}], destinos: [{id:1,n:"Crece solo",e:"⬆️"},{id:2,n:"Se pone encima",e:"🧤"}] },
    { p: "¿Líquido o Sólido en el cuerpo?", items: [{n:"Sangre",q:"blood",c:1,e:"🩸"},{n:"Hueso",q:"bone",c:2,e:"🦴"},{n:"Saliva",q:"spit",c:1,e:"💦"},{n:"Diente",q:"tooth",c:2,e:"🦷"}], destinos: [{id:1,n:"Líquido",e:"💧"},{id:2,n:"Sólido",e:"📦"}] },

    // === 4. NATURALEZA (15 retos) ===
    { p: "¿Qué ropa usamos?", items: [{n:"Abrigo",q:"coat",c:1,e:"🧥"},{n:"Bañador",q:"swimsuit",c:2,e:"🩱"},{n:"Bufanda",q:"scarf",c:1,e:"🧣"},{n:"Gorra",q:"cap",c:2,e:"🧢"}], destinos: [{id:1,n:"Frío",e:"❄️"},{id:2,n:"Calor",e:"☀️"}] },
    { p: "¿Qué trae agua?", items: [{n:"Lluvia",q:"rain",c:1,e:"🌧️"},{n:"Sol",q:"sun",c:2,e:"☀️"},{n:"Nieve",q:"snow",c:1,e:"❄️"},{n:"Viento",q:"wind",c:2,e:"💨"}], destinos: [{id:1,n:"Trae Agua",e:"💧"},{id:2,n:"Seco",e:"🌵"}] },
    { p: "¿Es una estación del año?", items: [{n:"Primavera",q:"spring",c:1,e:"🌸"},{n:"Lunes",q:"calendar",c:2,e:"📅"},{n:"Otoño",q:"autumn",e:"🍂"},{n:"Invierno",q:"winter",c:1,e:"❄️"},{n:"Verano",q:"summer",e:"☀️"}], destinos: [{id:1,n:"Estación",e:"📅"},{id:2,n:"No lo es",e:"❌"}] },
    { p: "¿Qué es un Fenómeno Natural?", items: [{n:"Trueno",q:"thunder",c:1,e:"🌩️"},{n:"Nube",q:"cloud",c:2,e:"☁️"},{n:"Tornado",q:"tornado",c:1,e:"🌪️"},{n:"Rayo",q:"lightning",c:1,e:"⚡"}], destinos: [{id:1,n:"Fenómeno",e:"🌦️"},{id:2,n:"No es fenómeno",e:"❌"}] },
    { p: "¿Qué necesita una PLANTA?", items: [{n:"Agua",q:"water",c:1,e:"💧"},{n:"Sol",q:"sun",c:1,e:"☀️"},{n:"Piedra",q:"stone",c:2,e:"🪨"},{n:"Aire",q:"air",c:1,e:"🌬️"}], destinos: [{id:1,n:"Necesario",e:"✅"},{id:2,n:"No es esencial",e:"❌"}] },
    { p: "¿Parte de la Planta?", items: [{n:"Raíz",q:"root",c:1,e:"🌱"},{n:"Hoja",q:"leaf",c:1,e:"🍃"},{n:"Coche",q:"car",c:2,e:"🚗"},{n:"Flor",q:"flower",c:1,e:"🌸"}], destinos: [{id:1,n:"Parte de Planta",e:"🌳"},{id:2,n:"No es planta",e:"❌"}] },
    { p: "¿Qué vemos en PRIMAVERA?", items: [{n:"Flores",q:"flowers",c:1,e:"🌸"},{n:"Nieve",q:"snow",c:2,e:"❄️"},{n:"Nidos",q:"nest",c:1,e:"🪺"},{n:"Abrigos",q:"coat",c:2,e:"🧥"}], destinos: [{id:1,n:"Primavera",e:"🌷"},{id:2,n:"Invierno",e:"❄️"}] },
    { p: "¿Qué es un CICLO natural?", items: [{n:"Lluvia",q:"rain",c:1,e:"🌧️"},{n:"Caminar",q:"walking",c:2,e:"🚶"},{n:"Tormenta",q:"storm",c:1,e:"⛈️"},{n:"Jugar",q:"play",c:2,e:"🎲"}], destinos: [{id:1,n:"Ciclo",e:"🔄"},{id:2,n:"Acción humana",e:"👤"}] },
    { p: "¿Luz Natural o Artificial?", items: [{n:"Sol",q:"sun",c:1,e:"☀️"},{n:"Bombilla",q:"bulb",c:2,e:"💡"},{n:"Estrellas",q:"star",c:1,e:"✨"},{n:"Linterna",q:"flashlight",c:2,e:"🔦"}], destinos: [{id:1,n:"De la Naturaleza",e:"🌿"},{id:2,n:"Del hombre",e:"🛠️"}] },
    { p: "¿Árbol o Flor?", items: [{n:"Pino",q:"pine",c:1,e:"🌲"},{n:"Rosa",q:"rose",c:2,e:"🌹"},{n:"Encina",q:"oak",c:1,e:"🌳"},{n:"Margarita",q:"daisy",c:2,e:"🌼"}], destinos: [{id:1,n:"Árbol",e:"🌳"},{id:2,n:"Flor",e:"🌸"}] },
    { p: "¿En qué estado está el agua?", items: [{n:"Hielo",q:"ice",c:1,e:"🧊"},{n:"Lluvia",q:"rain",c:2,e:"🌧️"},{n:"Nieve",q:"snow",c:1,e:"❄️"},{n:"Grifo",q:"water",c:2,e:"🚰"}], destinos: [{id:1,n:"Sólida",e:"🧊"},{id:2,n:"Líquida",e:"💧"}] },
    { p: "¿Qué hay en un bosque?", items: [{n:"Árbol",q:"tree",c:1,e:"🌳"},{n:"Edificio",q:"building",c:2,e:"🏢"},{n:"Río",q:"river",c:1,e:"🏞️"},{n:"Semáforo",q:"traffic-light",c:2,e:"🚥"}], destinos: [{id:1,n:"Naturaleza",e:"🌲"},{id:2,n:"Ciudad",e:"🏙️"}] },
    { p: "¿Animal o Planta?", items: [{n:"Conejito",q:"rabbit",c:1,e:"🐰"},{n:"Arbusto",q:"bush",c:2,e:"🌿"},{n:"Gatito",q:"cat",c:1,e:"🐱"},{n:"Césped",q:"grass",c:2,e:"🌱"}], destinos: [{id:1,n:"Animal",e:"🐾"},{id:2,n:"Planta",e:"🍃"}] },
    { p: "¿Hojas Verdes o Marrones?", items: [{n:"Verano",q:"summer",c:1,e:"☀️"},{n:"Otoño",q:"autumn",c:2,e:"🍂"}], destinos: [{id:1,n:"Verde",e:"🟢"},{id:2,n:"Marrón",e:"🟫"}] },
    { p: "¿Qué necesita el Aire?", items: [{n:"Viento",q:"wind",c:1,e:"💨"},{n:"Nube",q:"cloud",c:1,e:"☁️"},{n:"Piedra",q:"stone",c:2,e:"🪨"}], destinos: [{id:1,n:"Está en el aire",e:"☁️"},{id:2,n:"Está en el suelo",e:"🌍"}] },

    // === 5. CIUDAD Y OFICIOS (15 retos) ===
    { p: "¿Por dónde viajan?", items: [{n:"Coche",q:"car",c:1,e:"🚗"},{n:"Barco",q:"ship",c:2,e:"🚢"},{n:"Avión",q:"plane",c:3,e:"✈️"},{n:"Tren",q:"train",c:1,e:"🚆"}], destinos: [{id:1,n:"Tierra",e:"🛣️"},{id:2,n:"Mar",e:"🌊"},{id:3,n:"Aire",e:"☁️"}] },
    { p: "¿Dónde trabajan?", items: [{n:"Médico",q:"doctor",c:1,e:"👩‍⚕️"},{n:"Maestra",q:"teacher",c:2,e:"👩‍🏫"},{n:"Enfermera",q:"nurse",c:1,e:"🏥"},{n:"Alumno",q:"student",c:2,e:"🏫"}], destinos: [{id:1,n:"Hospital",e:"🏥"},{id:2,n:"Colegio",e:"🏫"}] },
    { p: "¿Qué herramientas usan?", items: [{n:"Manguera",q:"hose",c:1,e:"👩‍🚒"},{n:"Sartén",q:"pan",c:2,e:"🍳"},{n:"Camión rojo",q:"fire-truck",c:1,e:"🚒"},{n:"Gorro de chef",q:"chef-hat",c:2,e:"👨‍🍳"}], destinos: [{id:1,n:"Bombero",e:"👨‍🚒"},{id:2,n:"Cocinero",e:"👨‍🍳"}] },
    { p: "¿Qué vehículo es de EMERGENCIAS?", items: [{n:"Ambulancia",q:"ambulance",c:1,e:"🚑"},{n:"Coche familiar",q:"car",c:2,e:"🚗"},{n:"Coche policía",q:"police-car",c:1,e:"🚓"},{n:"Autobús",q:"bus",c:2,e:"🚌"}], destinos: [{id:1,n:"Ayuda rápido",e:"🚨"},{id:2,n:"Transporte normal",e:"🚲"}] },
    { p: "¿Es un medio de transporte?", items: [{n:"Bicicleta",q:"bike",c:1,e:"🚲"},{n:"Silla",q:"chair",c:2,e:"🪑"},{n:"Moto",q:"motorcycle",c:1,e:"🏍️"},{n:"Mesa",q:"table",c:2,e:"🍽️"}], destinos: [{id:1,n:"Para viajar",e:"🚀"},{id:2,n:"Mueble",e:"🏠"}] },
    { p: "¿En qué tienda se vende?", items: [{n:"Pan",q:"bread",c:1,e:"🍞"},{n:"Manzana",q:"apple",c:2,e:"🍎"},{n:"Barra",q:"baguette",c:1,e:"🥖"},{n:"Plátano",q:"banana",c:2,e:"🍌"}], destinos: [{id:1,n:"Panadería",e:"🥖"},{id:2,n:"Frutería",e:"🍇"}] },
    { p: "¿Qué hay en la calle?", items: [{n:"Farola",q:"streetlight",c:1,e:"💡"},{n:"Cama",q:"bed",c:2,e:"🛌"},{n:"Semáforo",q:"traffic-light",c:1,e:"🚦"},{n:"Ducha",q:"shower",c:2,e:"🚿"}], destinos: [{id:1,n:"En la calle",e:"🛣️"},{id:2,n:"En casa",e:"🏠"}] },
    { p: "¿Qué uniforme usan?", items: [{n:"Policía",q:"police",c:1,e:"👮"},{n:"Astronauta",q:"astronaut",c:2,e:"👨‍🚀"},{n:"Placa",q:"badge",c:1,e:"🛡️"},{n:"Casco espacial",q:"space-helmet",c:2,e:"🪖"}], destinos: [{id:1,n:"Policía",e:"👮"},{id:2,n:"Astronauta",e:"🚀"}] },
    { p: "¿Qué servicio nos dan?", items: [{n:"Carta",q:"letter",c:1,e:"✉️"},{n:"Basura",q:"trash",c:2,e:"🗑️"},{n:"Buzón",q:"mailbox",c:1,e:"📮"},{n:"Camión basura",q:"garbage-truck",c:2,e:"🚛"}], destinos: [{id:1,n:"Correos",e:"📬"},{id:2,n:"Limpieza",e:"🧹"}] },
    { p: "¿Es un animal o un trabajo?", items: [{n:"Pintor",q:"painter",c:2,e:"👨‍🎨"},{n:"Gato",q:"cat",c:1,e:"🐱"},{n:"Dentista",q:"dentist",c:2,e:"🦷"},{n:"Perro",q:"dog",c:1,e:"🐶"}], destinos: [{id:1,n:"Animal",e:"🐾"},{id:2,n:"Profesión",e:"👷"}] },
    { p: "¿Pueblo o Ciudad?", items: [{n:"Rascacielos",q:"skyscraper",c:2,e:"🏢"},{n:"Tractor",q:"tractor",c:1,e:"🚜"},{n:"Metro",q:"subway",c:2,e:"🚇"},{n:"Huerto",q:"garden",c:1,e:"🌱"}], destinos: [{id:1,n:"Pueblo/Campo",e:"👩‍🌾"},{id:2,n:"Gran Ciudad",e:"🏙️"}] },
    { p: "¿Qué herramienta usa el carpintero?", items: [{n:"Martillo",q:"hammer",c:1,e:"🔨"},{n:"Tijeras cocina",q:"scissors",c:2,e:"✂️"},{n:"Sierra",q:"saw",c:1,e:"🪚"},{n:"Cuchara",q:"spoon",c:2,e:"🥄"}], destinos: [{id:1,n:"Carpintero",e:"🪵"},{id:2,n:"Cocinero",e:"🍳"}] },
    { p: "¿Es dinero?", items: [{n:"Billete",q:"bill",c:1,e:"💵"},{n:"Hoja árbol",q:"leaf",c:2,e:"🍃"},{n:"Moneda",q:"coin",c:1,e:"🪙"},{n:"Piedra",q:"stone",c:2,e:"🪨"}], destinos: [{id:1,n:"Dinero",e:"💰"},{id:2,n:"No es dinero",e:"❌"}] },
    { p: "¿Dónde aparcan?", items: [{n:"Avión",q:"airplane",c:1,e:"✈️"},{n:"Tren",q:"train",c:2,e:"🚆"},{n:"Helicóptero",q:"helicopter",c:1,e:"🚁"},{n:"Vagón",q:"wagon",c:2,e:"🚃"}], destinos: [{id:1,n:"Aeropuerto",e:"🛫"},{id:2,n:"Estación",e:"🚉"}] },
    { p: "¿Qué usa el pintor?", items: [{n:"Pincel",q:"brush",c:1,e:"🖌️"},{n:"Paleta",q:"palette",c:1,e:"🎨"},{n:"Manguera",q:"hose",c:2,e:"🚒"},{n:"Escalera fuego",q:"ladder",c:2,e:"🪜"}], destinos: [{id:1,n:"Pintor",e:"👨‍🎨"},{id:2,n:"Bombero",e:"👩‍🚒"}] },

    // === 6. MATERIALES Y ENERGÍA (15 retos) ===
    { p: "¿De qué está hecho?", items: [{n:"Vaso",q:"glass",c:1,e:"🥛"},{n:"Mesa",q:"table",c:2,e:"🪵"},{n:"Ventana",q:"window",c:1,e:"🪟"},{n:"Lápiz",q:"pencil",c:2,e:"✏️"}], destinos: [{id:1,n:"Cristal",e:"🧪"},{id:2,n:"Madera",e:"🌳"}] },
    { p: "¿Qué usa ELECTRICIDAD?", items: [{n:"Tele",q:"tv",c:1,e:"📺"},{n:"Libro",q:"book",c:2,e:"📖"},{n:"Nevera",q:"fridge",c:1,e:"🧊"},{n:"Pelota",q:"ball",c:2,e:"⚽"}], destinos: [{id:1,n:"Enchufado",e:"🔌"},{id:2,n:"Sin cables",e:"🧸"}] },
    { p: "¿Es metal?", items: [{n:"Llave",q:"key",c:1,e:"🔑"},{n:"Cojín",q:"cushion",c:2,e:"☁️"},{n:"Cuchara",q:"spoon",c:1,e:"🥄"},{n:"Oso peluche",q:"teddy",c:2,e:"🧸"}], destinos: [{id:1,n:"Metal",e:"⚙️"},{id:2,n:"Tela/Blando",e:"🧵"}] },
    { p: "¿Natural o Fabricado?", items: [{n:"Roca",q:"rock",c:1,e:"🪨"},{n:"Coche",q:"car",c:2,e:"🚗"},{n:"Manzana",q:"apple",c:1,e:"🍎"},{n:"Robot",q:"robot",c:2,e:"🤖"}], destinos: [{id:1,n:"Naturaleza",e:"🌿"},{id:2,n:"Fábrica",e:"🏭"}] },
    { p: "¿Pesa mucho o poco?", items: [{n:"Elefante",q:"elephant",c:1,e:"🐘"},{n:"Pluma",q:"feather",c:2,e:"🪶"},{n:"Camión",q:"truck",c:1,e:"🚛"},{n:"Globo",q:"balloon",c:2,e:"🎈"}], destinos: [{id:1,n:"Pesado",e:"🏋️"},{id:2,n:"Ligero",e:"🍃"}] },
    { p: "¿De qué animal viene?", items: [{n:"Jersey",q:"sweater",c:1,e:"🧶"},{n:"Queso",q:"cheese",c:2,e:"🧀"},{n:"Lana",q:"wool",c:1,e:"🐑"},{n:"Leche",q:"milk",c:2,e:"🥛"}], destinos: [{id:1,n:"De la Oveja",e:"🐑"},{id:2,n:"De la Vaca",e:"🐮"}] },
    { p: "¿Es transparente?", items: [{n:"Cristal",q:"glass",c:1,e:"🪟"},{n:"Pared",q:"wall",c:2,e:"🧱"},{n:"Agua limpia",q:"water",c:1,e:"💧"},{n:"Puerta madera",q:"door",c:2,e:"🚪"}], destinos: [{id:1,n:"Se ve a través",e:"👓"},{id:2,n:"No se ve",e:"🌑"}] },
    { p: "¿Atrae el IMÁN?", items: [{n:"Tornillo",q:"screw",c:1,e:"🔩"},{n:"Goma",q:"eraser",c:2,e:"🧼"},{n:"Clavo",q:"nail",c:1,e:"🔨"},{n:"Papel",q:"paper",c:2,e:"📄"}], destinos: [{id:1,n:"Se pega",e:"🧲"},{id:2,n:"No se pega",e:"❌"}] },
    { p: "¿Es flexible (se dobla)?", items: [{n:"Regla plástico",q:"ruler",c:1,e:"📏"},{n:"Lápiz",q:"pencil",c:2,e:"✏️"},{n:"Goma pelo",q:"scrunchie",c:1,e:"➰"},{n:"Palo",q:"stick",c:2,e:"🪵"}], destinos: [{id:1,n:"Se dobla",e:"↪️"},{id:2,n:"Es rígido",e:"📏"}] },
    { p: "¿De qué planta viene?", items: [{n:"Papel",q:"paper",c:1,e:"📄"},{n:"Zumo",q:"juice",c:2,e:"🧃"},{n:"Mesa",q:"table",c:1,e:"🪵"},{n:"Mermelada",q:"jam",c:2,e:"🍯"}], destinos: [{id:1,n:"Del Árbol",e:"🌳"},{id:2,n:"De la Fruta",e:"🍎"}] },
    { p: "¿Flota o se hunde?", items: [{n:"Corcho",q:"cork",c:1,e:"🍾"},{n:"Piedra",q:"stone",c:2,e:"🪨"},{n:"Barco papel",q:"paper-boat",c:1,e:"⛵"},{n:"Llave metal",q:"key",c:2,e:"🔑"}], destinos: [{id:1,n:"Flota",e:"🛶"},{id:2,n:"Se hunde",e:"⚓"}] },
    { p: "¿Frío o Caliente?", items: [{n:"Hielo",q:"ice",c:1,e:"🧊"},{n:"Fuego",q:"fire",c:2,e:"🔥"},{n:"Helado",q:"ice-cream",c:1,e:"🍦"},{n:"Estufa",q:"heater",c:2,e:"🔥"}], destinos: [{id:1,n:"Frío",e:"❄️"},{id:2,n:"Calor",e:"🥵"}] },
    { p: "¿Da Luz?", items: [{n:"Sol",q:"sun",c:1,e:"☀️"},{n:"Silla",q:"chair",c:2,e:"🪑"},{n:"Linterna",q:"flashlight",c:1,e:"🔦"},{n:"Libro",q:"book",c:2,e:"📖"}], destinos: [{id:1,n:"Ilumina",e:"💡"},{id:2,n:"No da luz",e:"🌑"}] },
    { p: "¿A qué cubo va?", items: [{n:"Lata",q:"can",c:1,e:"🥫"},{n:"Revista",q:"magazine",c:2,e:"📖"},{n:"Brik",q:"milk-carton",c:1,e:"🧃"},{n:"Sobre",q:"envelope",c:2,e:"✉️"}], destinos: [{id:1,n:"Amarillo",e:"🟨"},{id:2,n:"Azul",e:"🟦"}] },
    { p: "¿Usa Pilas?", items: [{n:"Mando TV",q:"remote",c:1,e:"🎮"},{n:"Pelota",q:"ball",c:2,e:"⚽"},{n:"Coche juguete",q:"toy-car",c:1,e:"🏎️"},{n:"Bicicleta",q:"bike",c:2,e:"🚲"}], destinos: [{id:1,n:"Con Pilas",e:"🔋"},{id:2,n:"Sin pilas",e:"🤸"}] }
],


"relacionar": [
        // === 1. ANIMALES (15 retos) ===
        { p: "¿Tienen huesos (Vertebrados) o no (Invertebrados)?", izq: [{id:1,n:"Perro",e:"🐶"},{id:1,n:"Pez",e:"🐟"},{id:1,n:"Pájaro",e:"🐦"},{id:1,n:"Serpiente",e:"🐍"},{id:2,n:"Araña",e:"🕷️"},{id:2,n:"Caracol",e:"🐌"},{id:2,n:"Hormiga",e:"🐜"}], der: [{id:1,n:"Vertebrados",e:"🦴"},{id:2,n:"Invertebrados",e:"🐜"}] },
        { p: "¿Qué comen estos animales?", izq: [{id:1,n:"León",e:"🦁"},{id:1,n:"Tiburón",e:"🦈"},{id:1,n:"Lobo",e:"🐺"},{id:2,n:"Vaca",e:"🐄"},{id:2,n:"Elefante",e:"🐘"},{id:2,n:"Conejo",e:"🐰"},{id:2,n:"Oveja",e:"🐑"}], der: [{id:1,n:"Carnívoros",e:"🥩"},{id:2,n:"Herbívoros",e:"🌿"}] },
        { p: "¿Nacen de un huevo o de la mamá?", izq: [{id:1,n:"Gallina",e:"🐔"},{id:1,n:"Tortuga",e:"🐢"},{id:1,n:"Pato",e:"🦆"},{id:1,n:"Pez",e:"🐟"},{id:2,n:"Gato",e:"🐱"},{id:2,n:"Perro",e:"🐶"},{id:2,n:"Vaca",e:"🐮"}], der: [{id:1,n:"Del Huevo",e:"🥚"},{id:2,n:"De la Mamá",e:"🤱"}] },
        { p: "¿Es una mascota o es salvaje?", izq: [{id:1,n:"Perro",e:"🐶"},{id:1,n:"Gato",e:"🐱"},{id:1,n:"Hámster",e:"🐹"},{id:1,n:"Canario",e:"🐦"},{id:2,n:"León",e:"🦁"},{id:2,n:"Tigre",e:"🐯"},{id:2,n:"Elefante",e:"🐘"}], der: [{id:1,n:"Mascota",e:"🏠"},{id:2,n:"Salvaje",e:"🌴"}] },
        { p: "¿Dónde viven estos animales?", izq: [{id:1,n:"Ballena",e:"🐳"},{id:1,n:"Tiburón",e:"🦈"},{id:1,n:"Pulpo",e:"🐙"},{id:2,n:"León",e:"🦁"},{id:2,n:"Cebra",e:"🦓"},{id:2,n:"Jirafa",e:"🦒"},{id:2,n:"Mono",e:"🐒"}], der: [{id:1,n:"En el Mar",e:"🌊"},{id:2,n:"En la Tierra",e:"🌳"}] },
        { p: "¿Qué tienen en el cuerpo?", izq: [{id:1,n:"Perro",e:"🐶"},{id:1,n:"Gato",e:"🐱"},{id:1,n:"Oso",e:"🐻"},{id:2,n:"Pájaro",e:"🐦"},{id:2,n:"Loro",e:"🦜"},{id:3,n:"Pez",e:"🐟"},{id:3,n:"Serpiente",e:"🐍"}], der: [{id:1,n:"Pelo",e:"🐕"},{id:2,n:"Plumas",e:"🪶"},{id:3,n:"Escamas",e:"🦎"}] },
        { p: "¿Viven en la Granja o en la Selva?", izq: [{id:1,n:"Vaca",e:"🐄"},{id:1,n:"Cerdo",e:"🐷"},{id:1,n:"Gallina",e:"🐔"},{id:1,n:"Oveja",e:"🐑"},{id:2,n:"Gorila",e:"🦍"},{id:2,n:"Tigre",e:"🐯"},{id:2,n:"Cebra",e:"🦓"}], der: [{id:1,n:"Granja",e:"🚜"},{id:2,n:"Selva",e:"🌴"}] },
        { p: "¿Es un insecto o un mamífero?", izq: [{id:1,n:"Hormiga",e:"🐜"},{id:1,n:"Abeja",e:"🐝"},{id:1,n:"Mosca",e:"🪰"},{id:2,n:"Elefante",e:"🐘"},{id:2,n:"Perro",e:"🐶"},{id:2,n:"Ballena",e:"🐳"}], der: [{id:1,n:"Insectos",e:"🐞"},{id:2,n:"Mamíferos",e:"🐘"}] },
        { p: "¿Están despiertos de día o de noche?", izq: [{id:1,n:"Ardilla",e:"🐿️"},{id:1,n:"Pájaro",e:"🐦"},{id:1,n:"Mariposa",e:"🦋"},{id:2,n:"Búho",e:"🦉"},{id:2,n:"Murciélago",e:"🦇"},{id:2,n:"Zorro",e:"🦊"}], der: [{id:1,n:"De Día",e:"☀️"},{id:2,n:"De Noche",e:"🌙"}] },
        { p: "¿Comen carne, hierba o de todo?", izq: [{id:1,n:"Tigre",e:"🐯"},{id:1,n:"Lobo",e:"🐺"},{id:2,n:"Vaca",e:"🐄"},{id:2,n:"Oveja",e:"🐑"},{id:3,n:"Oso",e:"🐻"},{id:3,n:"Cerdo",e:"🐷"}], der: [{id:1,n:"Carnívoro",e:"🥩"},{id:2,n:"Herbívoro",e:"🌿"},{id:3,n:"Omnívoro",e:"🍎"}] },
        { p: "¿Cómo se desplazan?", izq: [{id:1,n:"Águila",e:"🦅"},{id:1,n:"Abeja",e:"🐝"},{id:2,n:"Caballo",e:"🐎"},{id:2,n:"Perro",e:"🐶"},{id:3,n:"Delfín",e:"🐬"},{id:3,n:"Pulpo",e:"🐙"}], der: [{id:1,n:"Vuelan",e:"☁️"},{id:2,n:"Caminan",e:"👣"},{id:3,n:"Nadan",e:"🌊"}] },
        { p: "¿Tienen patas o no?", izq: [{id:1,n:"Gato",e:"🐱"},{id:1,n:"Araña",e:"🕷️"},{id:1,n:"Pato",e:"🦆"},{id:2,n:"Serpiente",e:"🐍"},{id:2,n:"Pez",e:"🐟"},{id:2,n:"Gusano",e:"🪱"}], der: [{id:1,n:"Tienen patas",e:"👣"},{id:2,n:"No tienen",e:"❌"}] },
        { p: "¿Es Gigante o muy Pequeño?", izq: [{id:1,n:"Elefante",e:"🐘"},{id:1,n:"Ballena",e:"🐳"},{id:1,n:"Jirafa",e:"🦒"},{id:2,n:"Hormiga",e:"🐜"},{id:2,n:"Pulga",e:"🦟"},{id:2,n:"Abeja",e:"🐝"}], der: [{id:1,n:"Gigante",e:"🏔️"},{id:2,n:"Pequeñito",e:"🔍"}] },
        { p: "¿Son peligrosos para nosotros?", izq: [{id:1,n:"Tiburón",e:"🦈"},{id:1,n:"Cocodrilo",e:"🐊"},{id:1,n:"León",e:"🦁"},{id:2,n:"Conejo",e:"🐰"},{id:2,n:"Oveja",e:"🐑"},{id:2,n:"Pato",e:"🦆"}], der: [{id:1,n:"Peligro",e:"⚠️"},{id:2,n:"Amigable",e:"❤️"}] },
        { p: "¿Viven en el frío o en el calor?", izq: [{id:1,n:"Oso Polar",e:"🐻‍❄️"},{id:1,n:"Pingüino",e:"🐧"},{id:2,n:"Camello",e:"🐪"},{id:2,n:"Escorpión",e:"🦂"},{id:2,n:"Lagarto",e:"🦎"}], der: [{id:1,n:"Frío/Hielo",e:"❄️"},{id:2,n:"Calor/Desierto",e:"🌵"}] },

        // === 2. ESPACIO (15 retos) ===
        { p: "¿Es un Planeta o una Estrella?", izq: [{id:1,n:"Tierra",e:"🌍"},{id:1,n:"Marte",e:"🔴"},{id:1,n:"Júpiter",e:"🪐"},{id:1,n:"Saturno",e:"🪐"},{id:2,n:"Sol",e:"☀️"},{id:2,n:"Sirio",e:"✨"},{id:2,n:"Estrella Polar",e:"⭐"}], der: [{id:1,n:"Planetas",e:"🪐"},{id:2,n:"Estrellas",e:"☀️"}] },
        { p: "¿Es algo natural o un invento humano?", izq: [{id:1,n:"Estrella",e:"⭐"},{id:1,n:"Planeta",e:"🪐"},{id:1,n:"Cometa",e:"☄️"},{id:2,n:"Cohete",e:"🚀"},{id:2,n:"Telescopio",e:"🔭"},{id:2,n:"Satélite",e:"🛰️"}], der: [{id:1,n:"Naturaleza",e:"✨"},{id:2,n:"Invento Humano",e:"🛠️"}] },
        { p: "¿Qué vemos de día y qué de noche?", izq: [{id:1,n:"Sol",e:"☀️"},{id:1,n:"Arcoiris",e:"🌈"},{id:1,n:"Nube blanca",e:"☁️"},{id:2,n:"Luna",e:"🌙"},{id:2,n:"Estrellas",e:"✨"},{id:2,n:"Constelación",e:"🌌"}], der: [{id:1,n:"De Día",e:"🏙️"},{id:2,n:"De Noche",e:"🌃"}] },
        { p: "¿Está cerca o lejos de la Tierra?", izq: [{id:1,n:"Luna",e:"🌙"},{id:1,n:"Nube",e:"☁️"},{id:1,n:"Avión",e:"✈️"},{id:2,n:"Saturno",e:"🪐"},{id:2,n:"Galaxia",e:"🌌"},{id:2,n:"Estrellas lejanas",e:"✨"}], der: [{id:1,n:"Cerca",e:"🏡"},{id:2,n:"Muy Lejos",e:"🔭"}] },
        { p: "¿Es caliente o es frío?", izq: [{id:1,n:"El Sol",e:"☀️"},{id:1,n:"Estrella",e:"✨"},{id:1,n:"Fuego",e:"🔥"},{id:2,n:"Plutón",e:"❄️"},{id:2,n:"Hielo espacial",e:"🧊"},{id:2,n:"Urano",e:"🧊"}], der: [{id:1,n:"Mucho Calor",e:"🥵"},{id:2,n:"Mucho Frío",e:"🥶"}] },
        { p: "¿Es un Planeta Rocoso o de Gas?", izq: [{id:1,n:"Tierra",e:"🌍"},{id:1,n:"Marte",e:"🔴"},{id:1,n:"Mercurio",e:"🟤"},{id:2,n:"Júpiter",e:"🌬️"},{id:2,n:"Saturno",e:"🪐"}], der: [{id:1,n:"Duro (Roca)",e:"🪨"},{id:2,n:"Blando (Gas)",e:"☁️"}] },
        { p: "¿Gira alrededor del Sol o de la Tierra?", izq: [{id:1,n:"Tierra",e:"🌍"},{id:1,n:"Marte",e:"🔴"},{id:1,n:"Venus",e:"🟡"},{id:2,n:"La Luna",e:"🌙"},{id:2,n:"Satélite artificial",e:"🛰️"}], der: [{id:1,n:"Gira al Sol",e:"☀️"},{id:2,n:"Gira a la Tierra",e:"🌍"}] },
        { p: "¿Tiene anillos o no tiene?", izq: [{id:1,n:"Saturno",e:"🪐"},{id:1,n:"Urano",e:"🪐"},{id:2,n:"Tierra",e:"🌍"},{id:2,n:"Marte",e:"🔴"},{id:2,n:"Venus",e:"🟡"}], der: [{id:1,n:"Con Anillos",e:"⭕"},{id:2,n:"Sin Anillos",e:"❌"}] },
        { p: "¿De qué color se ve el astro?", izq: [{id:1,n:"Marte",e:"🔴"},{id:1,n:"Sangre",e:"🩸"},{id:2,n:"Tierra",e:"🌍"},{id:2,n:"Océano",e:"🌊"},{id:3,n:"Sol",e:"☀️"},{id:3,n:"Limón",e:"🍋"}], der: [{id:1,n:"Rojo",e:"🟥"},{id:2,n:"Azul",e:"🟦"},{id:3,n:"Amarillo",e:"🟨"}] },
        { p: "¿Es redondo o tiene otra forma?", izq: [{id:1,n:"Planeta",e:"🌍"},{id:1,n:"Luna Llena",e:"🌕"},{id:1,n:"Sol",e:"☀️"},{id:2,n:"Cohete",e:"🚀"},{id:2,n:"Estrella Fugaz",e:"🌠"},{id:2,n:"Telescopio",e:"🔭"}], der: [{id:1,n:"Esfera",e:"⚽"},{id:2,n:"No es esfera",e:"📐"}] },
        { p: "¿Flota o se cae al suelo (Gravedad)?", izq: [{id:1,n:"Astronauta",e:"👨‍🚀"},{id:1,n:"Nave",e:"🚀"},{id:1,n:"Satélite",e:"🛰️"},{id:2,n:"Manzana",e:"🍎"},{id:2,n:"Niña",e:"👧"},{id:2,n:"Piedra",e:"🪨"}], der: [{id:1,n:"Flota en Espacio",e:"🌌"},{id:2,n:"Cae en Tierra",e:"🌍"}] },
        { p: "¿Es Real o de Cuento?", izq: [{id:1,n:"Astronauta",e:"👨‍🚀"},{id:1,n:"Cohete",e:"🚀"},{id:1,n:"Telescopio",e:"🔭"},{id:2,n:"Marciano",e:"👽"},{id:2,n:"Hada",e:"🧚"},{id:2,n:"Dragón",e:"🐉"}], der: [{id:1,n:"Realidad",e:"✅"},{id:2,n:"Fantasía",e:"✨"}] },
        { p: "¿Sirve para mirar o para viajar?", izq: [{id:1,n:"Telescopio",e:"🔭"},{id:1,n:"Prismáticos",e:"👓"},{id:1,n:"Ojo",e:"👁️"},{id:2,n:"Cohete",e:"🚀"},{id:2,n:"Nave",e:"🛸"},{id:2,n:"Cápsula",e:"📦"}], der: [{id:1,n:"Para ver",e:"👀"},{id:2,n:"Para viajar",e:"🔥"}] },
        { p: "¿Brilla mucho o brilla poco?", izq: [{id:1,n:"El Sol",e:"☀️"},{id:1,n:"Sirio",e:"✨"},{id:2,n:"La Luna",e:"🌙"},{id:2,n:"Asteroide",e:"🪨"},{id:2,n:"Nube",e:"☁️"}], der: [{id:1,n:"Luz propia",e:"💡"},{id:2,n:"Sin luz propia",e:"🌑"}] },
        { p: "Relaciona los astros", izq: [{id:1,n:"Sol",e:"☀️"},{id:2,n:"Tierra",e:"🌍"},{id:3,n:"Luna",e:"🌙"}], der: [{id:1,n:"Estrella",e:"⭐"},{id:2,n:"Planeta",e:"🪐"},{id:3,n:"Satélite",e:"🛰️"}] },

        // === 3. CUERPO (15 retos) ===
        { p: "¿Está dentro o fuera de nuestro cuerpo?", izq: [{id:1,n:"Corazón",e:"❤️"},{id:1,n:"Cerebro",e:"🧠"},{id:1,n:"Huesos",e:"🦴"},{id:1,n:"Pulmones",e:"🫁"},{id:2,n:"Mano",e:"✋"},{id:2,n:"Nariz",e:"👃"},{id:2,n:"Ojo",e:"👁️"}], der: [{id:1,n:"Por dentro",e:"💀"},{id:2,n:"Por fuera",e:"👀"}] },
        { p: "¿Es un hábito Sano o Malo?", izq: [{id:1,n:"Comer fruta",e:"🍎"},{id:1,n:"Hacer deporte",e:"🏃"},{id:1,n:"Beber agua",e:"💧"},{id:1,n:"Dormir",e:"😴"},{id:2,n:"Muchos dulces",e:"🍭"},{id:2,n:"Mucha tele",e:"📺"},{id:2,n:"Gritar",e:"📢"}], der: [{id:1,n:"Saludable",e:"✅"},{id:2,n:"Perjudicial",e:"❌"}] },
        { p: "¿Es un Hueso, un Músculo o un Órgano?", izq: [{id:1,n:"Cráneo",e:"💀"},{id:1,n:"Fémur",e:"🦴"},{id:2,n:"Bíceps",e:"💪"},{id:2,n:"Lengua",e:"👅"},{id:3,n:"Corazón",e:"❤️"},{id:3,n:"Cerebro",e:"🧠"}], der: [{id:1,n:"Hueso",e:"🦴"},{id:2,n:"Músculo",e:"💪"},{id:3,n:"Órgano",e:"🫀"}] },
        { p: "¿De qué parte del cuerpo es?", izq: [{id:1,n:"Ojos",e:"👀"},{id:1,n:"Nariz",e:"👃"},{id:2,n:"Barriga",e:"👕"},{id:2,n:"Pecho",e:"👕"},{id:3,n:"Pies",e:"🦶"},{id:3,n:"Rodillas",e:"🦵"}], der: [{id:1,n:"Cabeza",e:"👤"},{id:2,n:"Tronco",e:"👕"},{id:3,n:"Extremidades",e:"🦵"}] },
        { p: "Relaciona el estímulo con el sentido", izq: [{id:1,n:"Caramelo",e:"🍭"},{id:2,n:"Perfume",e:"👃"},{id:3,n:"Arcoiris",e:"🌈"},{id:4,n:"Música",e:"🎵"},{id:5,n:"Peluche",e:"🧸"}], der: [{id:1,n:"Gusto",e:"👅"},{id:2,n:"Olfato",e:"👃"},{id:3,n:"Vista",e:"👁️"},{id:4,n:"Oído",e:"👂"},{id:5,n:"Tacto",e:"✋"}] },
        { p: "¿Es para Limpiarse o para Jugar?", izq: [{id:1,n:"Jabón",e:"🧼"},{id:1,n:"Pasta dientes",e:"🪥"},{id:1,n:"Esponja",e:"🧽"},{id:2,n:"Balón",e:"⚽"},{id:2,n:"Muñeca",e:"🪆"},{id:2,n:"Puzle",e:"🧩"}], der: [{id:1,n:"Higiene",e:"✨"},{id:2,n:"Juego",e:"🎨"}] },
        { p: "¿Está Arriba o Abajo?", izq: [{id:1,n:"Gorra",e:"🧢"},{id:1,n:"Gafas",e:"👓"},{id:1,n:"Peine",e:"🪮"},{id:2,n:"Zapatos",e:"👟"},{id:2,n:"Calcetines",e:"🧦"},{id:2,n:"Pantalón",e:"👖"}], der: [{id:1,n:"Superior",e:"👤"},{id:2,n:"Inferior",e:"🦵"}] },
        { p: "¿Es Sólido o Líquido en el cuerpo?", izq: [{id:1,n:"Dientes",e:"🦷"},{id:1,n:"Huesos",e:"🦴"},{id:1,n:"Uñas",e:"💅"},{id:2,n:"Sangre",e:"🩸"},{id:2,n:"Lágrimas",e:"💧"},{id:2,n:"Saliva",e:"💦"}], der: [{id:1,n:"Duro/Sólido",e:"📦"},{id:2,n:"Agua/Líquido",e:"💧"}] },
        { p: "¿Es Duro o Blando?", izq: [{id:1,n:"Cráneo",e:"💀"},{id:1,n:"Diente",e:"🦷"},{id:2,n:"Moflete",e:"😊"},{id:2,n:"Lengua",e:"👅"},{id:2,n:"Panza",e:"🤰"}], der: [{id:1,n:"Duro",e:"💪"},{id:2,n:"Blando",e:"🧸"}] },
        { p: "¿Qué órgano nos ayuda?", izq: [{id:1,n:"Para pensar",e:"💡"},{id:2,n:"Para respirar",e:"🌬️"},{id:3,n:"Para comer",e:"🍎"},{id:4,n:"Para bombear",e:"💓"}], der: [{id:1,n:"Cerebro",e:"🧠"},{id:2,n:"Pulmones",e:"🫁"},{id:3,n:"Estómago",e:"🍲"},{id:4,n:"Corazón",e:"❤️"}] },
        { p: "¿Deporte o Descanso?", izq: [{id:1,n:"Correr",e:"🏃"},{id:1,n:"Nadar",e:"🏊"},{id:1,n:"Bici",e:"🚲"},{id:2,n:"Dormir",e:"😴"},{id:2,n:"Sentarse",e:"🪑"},{id:2,n:"Siesta",e:"🛌"}], der: [{id:1,n:"Moverse",e:"🔥"},{id:2,n:"Descansar",e:"💤"}] },
        { p: "Relaciona el sentido con el órgano", izq: [{id:1,n:"Oír",e:"👂"},{id:2,n:"Ver",e:"👁️"},{id:3,n:"Tocar",e:"✋"},{id:4,n:"Oler",e:"👃"},{id:5,n:"Gustar",e:"👅"}], der: [{id:1,n:"Oreja",e:"👂"},{id:2,n:"Ojo",e:"👁️"},{id:3,n:"Piel",e:"✋"},{id:4,n:"Nariz",e:"👃"},{id:5,n:"Lengua",e:"👅"}] },
        { p: "¿Qué usamos en cada estación?", izq: [{id:1,n:"Abrigo",e:"🧥"},{id:1,n:"Bufanda",e:"🧣"},{id:2,n:"Bañador",e:"🩱"},{id:2,n:"Gafas de sol",e:"🕶️"}], der: [{id:1,n:"Mucho Frío",e:"❄️"},{id:2,n:"Mucho Calor",e:"☀️"}] },
        { p: "¿Crece solo o se pone encima?", izq: [{id:1,n:"Pelo",e:"💇"},{id:1,n:"Uñas",e:"💅"},{id:2,n:"Gorra",e:"🧢"},{id:2,n:"Reloj",e:"⌚"},{id:2,n:"Camiseta",e:"👕"}], der: [{id:1,n:"Es parte mía",e:"🧍"},{id:2,n:"Es ropa/accesorio",e:"🧤"}] },
        { p: "¿Tenemos 1 o tenemos 2?", izq: [{id:1,n:"Nariz",e:"👃"},{id:1,n:"Boca",e:"👄"},{id:1,n:"Lengua",e:"👅"},{id:2,n:"Ojos",e:"👀"},{id:2,n:"Orejas",e:"👂"},{id:2,n:"Manos",e:"🙌"}], der: [{id:1,n:"Solo Uno",e:"1️⃣"},{id:2,n:"Dos (Pareja)",e:"2️⃣"}] },

        // === 4. NATURALEZA (15 retos) ===
        { p: "¿De qué estación es cada cosa?", izq: [{id:1,n:"Nieve",e:"❄️"},{id:1,n:"Abrigo",e:"🧥"},{id:1,n:"Gorro",e:"🧶"},{id:2,n:"Bañador",e:"🩱"},{id:2,n:"Sombrilla",e:"⛱️"},{id:2,n:"Helado",e:"🍦"},{id:2,n:"Gafas de sol",e:"🕶️"}], der: [{id:1,n:"Invierno",e:"⛄"},{id:2,n:"Verano",e:"☀️"}] },
        { p: "¿Trae agua o hace calor?", izq: [{id:1,n:"Lluvia",e:"🌧️"},{id:1,n:"Nieve",e:"❄️"},{id:1,n:"Tormenta",e:"⛈️"},{id:2,n:"Sol fuerte",e:"☀️"},{id:2,n:"Sequía",e:"🌵"},{id:2,n:"Desierto",e:"🏜️"}], der: [{id:1,n:"Mojado",e:"💧"},{id:2,n:"Seco",e:"🔥"}] },
        { p: "¿Viene del cielo o del suelo?", izq: [{id:1,n:"Lluvia",e:"🌧️"},{id:1,n:"Nieve",e:"❄️"},{id:1,n:"Rayo",e:"⚡"},{id:2,n:"Hierba",e:"🌿"},{id:2,n:"Piedra",e:"🪨"},{id:2,n:"Flor",e:"🌻"}], der: [{id:1,n:"Desde arriba",e:"☁️"},{id:2,n:"Desde abajo",e:"🌍"}] },
        { p: "¿Es de Primavera o de Invierno?", izq: [{id:1,n:"Flores",e:"🌻"},{id:1,n:"Mariposas",e:"🦋"},{id:1,n:"Nidos",e:"🪺"},{id:2,n:"Nieve",e:"❄️"},{id:2,n:"Hielo",e:"🧊"},{id:2,n:"Árbol sin hojas",e:"🪵"}], der: [{id:1,n:"Primavera",e:"🌷"},{id:2,n:"Invierno",e:"⛄"}] },
        { p: "¿Es parte de la planta o no?", izq: [{id:1,n:"Raíz",e:"🌱"},{id:1,n:"Hoja",e:"🍃"},{id:1,n:"Tallo",e:"🌳"},{id:2,n:"Coche",e:"🚗"},{id:2,n:"Piedra",e:"🪨"},{id:2,n:"Libro",e:"📖"}], der: [{id:1,n:"Sí es Planta",e:"🌿"},{id:2,n:"No es Planta",e:"❌"}] },
        { p: "¿Es Fenómeno Natural o Acción Humana?", izq: [{id:1,n:"Tornado",e:"🌪️"},{id:1,n:"Terremoto",e:"🌋"},{id:1,n:"Rayo",e:"⚡"},{id:2,n:"Caminar",e:"🚶"},{id:2,n:"Jugar",e:"🎲"},{id:2,n:"Estudiar",e:"📖"}], der: [{id:1,n:"Naturaleza",e:"🌍"},{id:2,n:"Persona",e:"👤"}] },
        { p: "¿Es un Árbol, una Flor o un Arbusto?", izq: [{id:1,n:"Pino",e:"🌲"},{id:1,n:"Palmera",e:"🌴"},{id:2,n:"Rosa",e:"🌹"},{id:2,n:"Margarita",e:"🌼"},{id:3,n:"Seto",e:"🌳"},{id:3,n:"Zarza",e:"🌿"}], der: [{id:1,n:"Árbol",e:"🌲"},{id:2,n:"Flor",e:"🌸"},{id:3,n:"Arbusto",e:"🌲"}] },
        { p: "¿De qué color es la hoja?", izq: [{id:1,n:"Verano",e:"🌳"},{id:1,n:"Primavera",e:"🌱"},{id:2,n:"Otoño",e:"🍂"},{id:2,n:"Hoja seca",e:"🍁"}], der: [{id:1,n:"Verde",e:"🟢"},{id:2,n:"Marrón",e:"🟫"}] },
        { p: "¿Viene del Sol o de la Nube?", izq: [{id:1,n:"Calor",e:"🔥"},{id:1,n:"Luz",e:"💡"},{id:2,n:"Lluvia",e:"🌧️"},{id:2,n:"Sombra",e:"👤"},{id:2,n:"Trueno",e:"📢"}], der: [{id:1,n:"Del Sol",e:"☀️"},{id:2,n:"De la Nube",e:"☁️"}] },
        { p: "¿Luz Natural o Luz Artificial?", izq: [{id:1,n:"Sol",e:"☀️"},{id:1,n:"Estrellas",e:"✨"},{id:1,n:"Rayo",e:"⚡"},{id:2,n:"Bombilla",e:"💡"},{id:2,n:"Linterna",e:"🔦"},{id:2,n:"Tele",e:"📺"}], der: [{id:1,n:"Naturaleza",e:"🌿"},{id:2,n:"Pilas/Enchufe",e:"🔌"}] },
        { p: "¿Es Paisaje de Montaña o de Playa?", izq: [{id:1,n:"Roca alta",e:"⛰️"},{id:1,n:"Nieve arriba",e:"❄️"},{id:2,n:"Arena",e:"🏖️"},{id:2,n:"Ola",e:"🌊"},{id:2,n:"Sombrilla",e:"⛱️"}], der: [{id:1,n:"Montaña",e:"⛰️"},{id:2,n:"Playa",e:"🏖️"}] },
        { p: "¿Es Sólido o Líquido?", izq: [{id:1,n:"Hielo",e:"🧊"},{id:1,n:"Granizo",e:"🧊"},{id:2,n:"Lluvia",e:"💧"},{id:2,n:"Río",e:"🏞️"},{id:2,n:"Mar",e:"🌊"}], der: [{id:1,n:"Duro",e:"📦"},{id:2,n:"Agua",e:"💧"}] },
        { p: "¿Huele rico o huele mal?", izq: [{id:1,n:"Flor",e:"🌸"},{id:1,n:"Pino",e:"🌲"},{id:2,n:"Zorrillo",e:"🦨"},{id:2,n:"Humo",e:"💨"}], der: [{id:1,n:"Bien",e:"😊"},{id:2,n:"Fuchi",e:"🤢"}] },
        { p: "¿Es necesario para la planta o no?", izq: [{id:1,n:"Sol",e:"☀️"},{id:1,n:"Agua",e:"💧"},{id:1,n:"Tierra",e:"🌍"},{id:2,n:"Mesa",e:"🍽️"},{id:2,n:"Coche",e:"🚗"},{id:2,n:"Zapatillas",e:"👟"}], der: [{id:1,n:"Lo necesita",e:"✅"},{id:2,n:"No lo quiere",e:"❌"}] },
        { p: "¿Es tiempo de Viento o de Calma?", izq: [{id:1,n:"Tornado",e:"🌪️"},{id:1,n:"Mueve hojas",e:"💨"},{id:1,n:"Vuela cometa",e:"🪁"},{id:2,n:"Día quieto",e:"☀️"},{id:2,n:"No hay aire",e:"🧍"}], der: [{id:1,n:"Viento",e:"💨"},{id:2,n:"Calma",e:"☀️"}] },

        // === 5. CIUDAD Y OFICIOS (15 retos) ===
        { p: "¿Por dónde viajan estos transportes?", izq: [{id:1,n:"Coche",e:"🚗"},{id:1,n:"Autobús",e:"🚌"},{id:1,n:"Bici",e:"🚲"},{id:2,n:"Avión",e:"✈️"},{id:2,n:"Cohete",e:"🚀"},{id:2,n:"Helicóptero",e:"🚁"},{id:3,n:"Barco",e:"🚢"}], der: [{id:1,n:"Tierra",e:"🛣️"},{id:2,n:"Aire",e:"☁️"},{id:3,n:"Mar",e:"🌊"}] },
        { p: "¿Dónde trabajan?", izq: [{id:1,n:"Médico",e:"👩‍⚕️"},{id:1,n:"Enfermera",e:"🏥"},{id:2,n:"Maestra",e:"👩‍🏫"},{id:2,n:"Alumno",e:"🧒"},{id:3,n:"Granjero",e:"👨‍🌾"},{id:3,n:"Vaca",e:"🐮"}], der: [{id:1,n:"Hospital",e:"🏥"},{id:2,n:"Colegio",e:"🏫"},{id:3,n:"Granja",e:"🚜"}] },
        { p: "¿Qué herramientas usa cada uno?", izq: [{id:1,n:"Pincel",e:"🖌️"},{id:1,n:"Paleta",e:"🎨"},{id:2,n:"Manguera",e:"🚿"},{id:2,n:"Camión rojo",e:"🚒"},{id:3,n:"Sartén",e:"🍳"},{id:3,n:"Cuchara",e:"🥄"}], der: [{id:1,n:"Pintor",e:"👨‍🎨"},{id:2,n:"Bombero",e:"👨‍🚒"},{id:3,n:"Cocinero",e:"👨‍🍳"}] },
        { p: "¿Es del Pueblo o de la Ciudad?", izq: [{id:1,n:"Tractor",e:"🚜"},{id:1,n:"Huerto",e:"🌱"},{id:1,n:"Poca gente",e:"🏘️"},{id:2,n:"Rascacielos",e:"🏢"},{id:2,n:"Metro/Tren",e:"🚇"},{id:2,n:"Muchos coches",e:"🚗"}], der: [{id:1,n:"Pueblo",e:"🏘️"},{id:2,n:"Ciudad",e:"🏙️"}] },
        { p: "¿Qué uniforme usan?", izq: [{id:1,n:"Placa",e:"🛡️"},{id:1,n:"Gorra azul",e:"👮"},{id:2,n:"Bata blanca",e:"🥼"},{id:2,n:"Termómetro",e:"🌡️"},{id:3,n:"Casco",e:"🪖"},{id:3,n:"Martillo",e:"🔨"}], der: [{id:1,n:"Policía",e:"👮"},{id:2,n:"Médico",e:"👩‍⚕️"},{id:3,n:"Albañil",e:"👷"}] },
        { p: "¿En qué tienda se vende?", izq: [{id:1,n:"Pan",e:"🍞"},{id:1,n:"Barra",e:"🥖"},{id:2,n:"Manzana",e:"🍎"},{id:2,n:"Plátano",e:"🍌"},{id:3,n:"Pastel",e:"🍰"},{id:3,n:"Tarta",e:"🎂"}], der: [{id:1,n:"Panadería",e:"🥖"},{id:2,n:"Frutería",e:"🍇"},{id:3,n:"Pastelería",e:"🧁"}] },
        { p: "¿Qué significan las luces del semáforo?", izq: [{id:1,n:"Luz Roja",e:"🔴"},{id:1,n:"Coche quieto",e:"✋"},{id:2,n:"Luz Verde",e:"🟢"},{id:2,n:"Coche pasa",e:"🚗"}], der: [{id:1,n:"Parar",e:"🛑"},{id:2,n:"Pasar",e:"✅"}] },
        { p: "¿Qué servicios hay en la ciudad?", izq: [{id:1,n:"Camión basura",e:"🚛"},{id:1,n:"Barrendero",e:"🧹"},{id:2,n:"Farola",e:"💡"},{id:2,n:"Cable",e:"🔌"}], der: [{id:1,n:"Limpieza",e:"✨"},{id:2,n:"Luz",e:"🔌"}] },
        { p: "¿Es para ayudar en emergencia?", izq: [{id:1,n:"Ambulancia",e:"🚑"},{id:1,n:"Coche Policía",e:"🚓"},{id:1,n:"Camión Bombero",e:"🚒"},{id:2,n:"Coche azul",e:"🚗"},{id:2,n:"Bici",e:"🚲"},{id:2,n:"Moto",e:"🏍️"}], der: [{id:1,n:"Sí, Ayuda",e:"🚨"},{id:2,n:"Transporte normal",e:"🏠"}] },
        { p: "¿Es Dinero?", izq: [{id:1,n:"Billete",e:"💵"},{id:1,n:"Moneda",e:"🪙"},{id:2,n:"Hoja árbol",e:"🍃"},{id:2,n:"Piedra",e:"🪨"},{id:2,n:"Cromos",e:"🃏"}], der: [{id:1,n:"Sirve para comprar",e:"💰"},{id:2,n:"No es dinero",e:"❌"}] },
        { p: "¿Herramientas de oficina o de obra?", izq: [{id:1,n:"Ordenador",e:"💻"},{id:1,n:"Lápiz",e:"✏️"},{id:1,n:"Papel",e:"📄"},{id:2,n:"Ladrillo",e:"🧱"},{id:2,n:"Grúa",e:"🏗️"},{id:2,n:"Hormigonera",e:"🚜"}], der: [{id:1,n:"Oficina",e:"💼"},{id:2,n:"Construcción",e:"🏗️"}] },
        { p: "¿De dónde salen los transportes?", izq: [{id:1,n:"Tren",e:"🚆"},{id:2,n:"Barco",e:"🚢"},{id:3,n:"Avión",e:"✈️"}], der: [{id:1,n:"Estación",e:"🚉"},{id:2,n:"Puerto",e:"⚓"},{id:3,n:"Aeropuerto",e:"🛫"}] },
        { p: "Profesiones de ayuda", izq: [{id:1,n:"Dentista",e:"🦷"},{id:2,n:"Veterinario",e:"🐾"},{id:3,n:"Peluquero",e:"💇"}], der: [{id:1,n:"Dientes",e:"🦷"},{id:2,n:"Animales",e:"🐶"},{id:3,n:"Cortar pelo",e:"✂️"}] },
        { p: "¿Cómo nos comunicamos?", izq: [{id:1,n:"Carta",e:"✉️"},{id:1,n:"Sello",e:"📮"},{id:2,n:"Teléfono",e:"📞"},{id:2,n:"Móvil",e:"📱"}], der: [{id:1,n:"Correos",e:"📬"},{id:2,n:"Llamar",e:"📞"}] },
        { p: "¿Qué hay en la calle o en casa?", izq: [{id:1,n:"Banco sentarse",e:"🪑"},{id:1,n:"Farola",e:"💡"},{id:1,n:"Semáforo",e:"🚦"},{id:2,n:"Cama",e:"🛏️"},{id:2,n:"Nevera",e:"🧊"},{id:2,n:"Sofá",e:"🛋️"}], der: [{id:1,n:"En la calle",e:"🛣️"},{id:2,n:"En mi casa",e:"🏠"}] },

        // === 6. MATERIALES Y ENERGÍA (15 retos) ===
        { p: "¿Es un material Sólido o Líquido?", izq: [{id:1,n:"Roca",e:"🪨"},{id:1,n:"Madera",e:"🪵"},{id:1,n:"Hielo",e:"🧊"},{id:1,n:"Hierro",e:"⚙️"},{id:2,n:"Agua",e:"💧"},{id:2,n:"Leche",e:"🥛"},{id:2,n:"Zumo",e:"🍹"}], der: [{id:1,n:"Sólido (Duro)",e:"📦"},{id:2,n:"Líquido (Agua)",e:"💧"}] },
        { p: "¿De qué material está hecho?", izq: [{id:1,n:"Vaso",e:"🥛"},{id:2,n:"Mesa",e:"🪵"},{id:3,n:"Clavo",e:"🔩"},{id:4,n:"Jersey",e:"🧶"},{id:5,n:"Neumático",e:"🛞"}], der: [{id:1,n:"Cristal",q:"glass"},{id:2,n:"Madera",q:"wood"},{id:3,n:"Metal",q:"metal"},{id:4,n:"Lana",q:"wool"},{id:5,n:"Goma",q:"rubber"}] },
        { p: "¿Qué usa Electricidad y qué Pilas?", izq: [{id:1,n:"Nevera",e:"🧊"},{id:1,n:"Tele",e:"📺"},{id:1,n:"Lámpara",e:"💡"},{id:2,n:"Mando",e:"🎮"},{id:2,n:"Linterna",e:"🔦"},{id:2,n:"Reloj muñeca",e:"⌚"}], der: [{id:1,n:"Enchufe",e:"🔌"},{id:2,n:"Pilas",e:"🔋"}] },
        { p: "¿De qué origen es el material?", izq: [{id:1,n:"Lana",e:"🧶"},{id:1,n:"Cuero",e:"👞"},{id:2,n:"Papel",e:"📄"},{id:2,n:"Mesa madera",e:"🪵"},{id:3,n:"Plástico",e:"🧴"}], der: [{id:1,n:"Animal",e:"🐑"},{id:2,n:"Planta",e:"🌳"},{id:3,n:"Fábrica",e:"🏭"}] },
        { p: "¿Pesa Mucho o Poco?", izq: [{id:1,n:"Elefante",e:"🐘"},{id:1,n:"Camión",e:"🚛"},{id:1,n:"Yunque",e:"🏗️"},{id:2,n:"Pluma",e:"🪶"},{id:2,n:"Globo",e:"🎈"},{id:2,n:"Burbuja",e:"🫧"}], der: [{id:1,n:"Pesado",e:"🏋️"},{id:2,n:"Ligero",e:"🍃"}] },
        { p: "¿Es Transparente o Opaco?", izq: [{id:1,n:"Cristal",e:"🪟"},{id:1,n:"Vaso vacío",e:"🥛"},{id:2,n:"Pared",e:"🧱"},{id:2,n:"Puerta madera",e:"🚪"},{id:2,n:"Caja cartón",e:"📦"}], der: [{id:1,n:"Veo a través",e:"👓"},{id:2,n:"No veo nada",e:"🌑"}] },
        { p: "¿Natural o Artificial?", izq: [{id:1,n:"Roca",e:"🪨"},{id:1,n:"Manzana",e:"🍎"},{id:1,n:"Tronco",e:"🪵"},{id:2,n:"Coche",e:"🚗"},{id:2,n:"Robot",e:"🤖"},{id:2,n:"Plástico",e:"🧴"}], der: [{id:1,n:"Naturaleza",e:"🌿"},{id:2,n:"Hecho por hombre",e:"🛠️"}] },
        { p: "¿Se pega al imán?", izq: [{id:1,n:"Clavo",e:"🔩"},{id:1,n:"Tornillo",e:"⚙️"},{id:1,n:"Clip",e:"📎"},{id:2,n:"Goma",e:"🧼"},{id:2,n:"Lápiz",e:"✏️"},{id:2,n:"Papel",e:"📄"}], der: [{id:1,n:"Sí se pega",e:"🧲"},{id:2,n:"No se pega",e:"❌"}] },
        { p: "¿Es Flexible o Rígido?", izq: [{id:1,n:"Goma pelo",e:"➰"},{id:1,n:"Papel",e:"📄"},{id:2,n:"Palo madera",e:"🪵"},{id:2,n:"Roca",e:"🪨"},{id:2,n:"Cristal",e:"🪟"}], der: [{id:1,n:"Se dobla",e:"↪️"},{id:2,n:"No se dobla",e:"📏"}] },
        { p: "¿Es Liso o Rugoso?", izq: [{id:1,n:"Espejo",e:"🪞"},{id:1,n:"Canica",e:"🔮"},{id:2,n:"Lija",e:"📄"},{id:2,n:"Piña pino",e:"🌲"},{id:2,n:"Tronco",e:"🪵"}], der: [{id:1,n:"Suave",e:"✨"},{id:2,n:"Raspa",e:"🌵"}] },
        { p: "¿Se derrite con calor?", izq: [{id:1,n:"Hielo",e:"🧊"},{id:1,n:"Helado",e:"🍦"},{id:1,n:"Chocolate",e:"🍫"},{id:2,n:"Roca",e:"🪨"},{id:2,n:"Madera",e:"🪵"},{id:2,n:"Metal",e:"⚙️"}], der: [{id:1,n:"Se hace agua",e:"💧"},{id:2,n:"No se derrite",e:"🧱"}] },
        { p: "¿Da Luz o Da Calor?", izq: [{id:1,n:"Bombilla",e:"💡"},{id:1,n:"Linterna",e:"🔦"},{id:2,n:"Estufa",e:"🔥"},{id:2,n:"Fuego",e:"🔥"},{id:2,n:"Radiador",e:"🌡️"}], der: [{id:1,n:"Luz",e:"💡"},{id:2,n:"Calor",e:"🥵"}] },
        { p: "¿Cubo de reciclaje?", izq: [{id:1,n:"Periódico",e:"📰"},{id:1,n:"Caja cartón",e:"📦"},{id:2,n:"Botella",e:"🧴"},{id:2,n:"Lata",e:"🥫"},{id:2,n:"Brik",e:"🧃"}], der: [{id:1,n:"Azul",e:"🟦"},{id:2,n:"Amarillo",e:"🟨"}] },
        { p: "¿Flota o se Hunde?", izq: [{id:1,n:"Barco papel",e:"⛵"},{id:1,n:"Corcho",e:"🍾"},{id:1,n:"Pato goma",e:"🐤"},{id:2,n:"Ancla",e:"⚓"},{id:2,n:"Piedra",e:"🪨"},{id:2,n:"Llave metal",e:"🔑"}], der: [{id:1,n:"Flota",e:"🛶"},{id:2,n:"Se hunde",e:"⚓"}] },
        { p: "¿Es Frágil o Resistente?", izq: [{id:1,n:"Vaso cristal",e:"🥛"},{id:1,n:"Huevo",e:"🥚"},{id:1,n:"Espejo",e:"🪞"},{id:2,n:"Martillo",e:"🔨"},{id:2,n:"Roca",e:"🪨"},{id:2,n:"Acero",e:"🔩"}], der: [{id:1,n:"Se rompe fácil",e:"💥"},{id:2,n:"No se rompe",e:"💪"}] }
    ],

"ordenar": [
        // === 1. ANIMALES (15 retos) ===
        { p: "Ciclo de la Rana", items: [{id:1,n:"Huevo",q:"frog-egg",e:"🥚"},{id:2,n:"Renacuajo",q:"tadpole",e:"🐟"},{id:3,n:"Rana joven",q:"small-frog",e:"🐸"},{id:4,n:"Rana adulta",q:"frog",e:"🐸"}] },
        { p: "Ciclo de la Mariposa", items: [{id:1,n:"Huevo",q:"egg",e:"🥚"},{id:2,n:"Oruga",q:"caterpillar",e:"🐛"},{id:3,n:"Crisálida",q:"chrysalis",e:"🏠"},{id:4,n:"Mariposa",q:"butterfly",e:"🦋"}] },
        { p: "Ciclo del Pollito", items: [{id:1,n:"Huevo",e:"🥚"},{id:2,n:"Saliendo",e:"🐣"},{id:3,n:"Pollito",e:"🐥"}] },
        { p: "Vida de un Perro", items: [{id:1,n:"Cachorro",e:"🐶"},{id:2,n:"Adulto",e:"🐕"},{id:3,n:"Anciano",e:"👴"}] },
        { p: "Tamaño: De pequeño a grande", items: [{id:1,n:"Hormiga",e:"🐜"},{id:2,n:"Gato",e:"🐱"},{id:3,n:"León",e:"🦁"},{id:4,n:"Elefante",e:"🐘"}] },
        { p: "Cadena alimentaria", items: [{id:1,n:"Hierba",e:"🌿"},{id:2,n:"Cebra",e:"🦓"},{id:3,n:"León",e:"🦁"}] },
        { p: "Velocidad: De lento a rápido", items: [{id:1,n:"Caracol",e:"🐌"},{id:2,n:"Perro",e:"🐶"},{id:3,n:"Guepardo",e:"🐆"}] },
        { p: "Nacimiento de un pájaro", items: [{id:1,n:"Nido",e:"🪺"},{id:2,n:"Huevo",e:"🥚"},{id:3,n:"Pajarito",e:"🐥"},{id:4,n:"Vuelo",e:"🐦"}] },
        { p: "De la oveja a la lana", items: [{id:1,n:"Oveja",e:"🐑"},{id:2,n:"Esquilar",e:"✂️"},{id:3,n:"Ovillo",e:"🧶"},{id:4,n:"Jersey",e:"👕"}] },
        { p: "Ciclo de la abeja", items: [{id:1,n:"Flor",e:"🌸"},{id:2,n:"Abeja",e:"🐝"},{id:3,n:"Colmena",e:"🍯"},{id:4,n:"Miel",e:"🍯"}] },
        { p: "Altura: De bajo a alto", items: [{id:1,n:"Pingüino",e:"🐧"},{id:2,n:"Cebra",e:"🦓"},{id:3,n:"Jirafa",e:"🦒"}] },
        { p: "Peso: De ligero a pesado", items: [{id:1,n:"Pájaro",e:"🐦"},{id:2,n:"Oso",e:"🐻"},{id:3,n:"Ballena",e:"🐳"}] },
        { p: "Ciclo de la seda", items: [{id:1,n:"Gusano",e:"🐛"},{id:2,n:"Capullo",e:"🧶"},{id:3,n:"Seda",e:"👗"}] },
        { p: "Dientes: De pocos a muchos", items: [{id:1,n:"Bebé",e:"👶"},{id:2,n:"Niño",e:"👦"},{id:3,n:"Cocodrilo",e:"🐊"}] },
        { p: "Pueblo a Selva", items: [{id:1,n:"Gato",e:"🐱"},{id:2,n:"Zorro",e:"🦊"},{id:3,n:"Tigre",e:"🐯"}] },

        // === 2. ESPACIO (15 retos) ===
        { p: "Ordena los planetas desde el Sol", items: [{id:1,n:"Mercurio",q:"mercury",e:"🟤"},{id:2,n:"Venus",q:"venus",e:"🟡"},{id:3,n:"Tierra",q:"earth",e:"🌍"},{id:4,n:"Marte",q:"mars",e:"🔴"}] },
        { p: "Tamaño: De pequeño a gigante", items: [{id:1,n:"Luna",q:"moon",e:"🌙"},{id:2,n:"Tierra",q:"earth",e:"🌍"},{id:3,n:"Júpiter",q:"jupiter",e:"🪐"},{id:4,n:"Sol",q:"sun",e:"☀️"}] },
        { p: "Despegue de un cohete", items: [{id:1,n:"Cuenta atrás",e:"🔢"},{id:2,n:"Fuego",e:"🔥"},{id:3,n:"Vuelo",e:"🚀"}] },
        { p: "Fases de la Luna", items: [{id:1,n:"Luna Nueva",e:"🌑"},{id:2,n:"Cuarto Creciente",e:"🌓"},{id:3,n:"Luna Llena",e:"🌕"}] },
        { p: "Misión espacial", items: [{id:1,n:"Entrenar",e:"🏃"},{id:2,n:"Vestirse",e:"👨‍🚀"},{id:3,n:"Subir nave",e:"🚀"},{id:4,n:"Espacio",e:"🌌"}] },
        { p: "Ciclo del día", items: [{id:1,n:"Amanecer",e:"🌅"},{id:2,n:"Mediodía",e:"☀️"},{id:3,n:"Atardecer",e:"🌇"},{id:4,n:"Noche",e:"🌃"}] },
        { p: "Distancia: De cerca a lejos", items: [{id:1,n:"Nube",e:"☁️"},{id:2,n:"Luna",e:"🌙"},{id:3,n:"Marte",e:"🔴"},{id:4,n:"Estrellas",e:"✨"}] },
        { p: "Llegada a la Luna", items: [{id:1,n:"Viaje",e:"🚀"},{id:2,n:"Aterrizaje",e:"🛰️"},{id:3,n:"Caminar",e:"👣"},{id:4,n:"Bandera",e:"🚩"}] },
        { p: "Brillo: De menos a más", items: [{id:1,n:"Roca",e:"🪨"},{id:2,n:"Luna",e:"🌙"},{id:3,n:"Sol",e:"☀️"}] },
        { p: "Las Estaciones", items: [{id:1,n:"Primavera",e:"🌸"},{id:2,n:"Verano",e:"☀️"},{id:3,n:"Otoño",e:"🍂"},{id:4,n:"Invierno",e:"❄️"}] },
        { p: "Camino de la luz", items: [{id:1,n:"Sol",e:"☀️"},{id:2,n:"Rayo de luz",e:"✨"},{id:3,n:"Tierra",e:"🌍"}] },
        { p: "Planetas por tamaño", items: [{id:1,n:"Marte",e:"🔴"},{id:2,n:"Tierra",e:"🌍"},{id:3,n:"Saturno",e:"🪐"}] },
        { p: "Observación", items: [{id:1,n:"Ojo",e:"👁️"},{id:2,n:"Prismáticos",e:"👓"},{id:3,n:"Telescopio",e:"🔭"}] },
        { p: "Formación de estrella", items: [{id:1,n:"Polvo",e:"💨"},{id:2,n:"Fuego",e:"🔥"},{id:3,n:"Estrella",e:"✨"}] },
        { p: "Gravedad: Donde flotas más", items: [{id:1,n:"Tierra",e:"🌍"},{id:2,n:"Luna",e:"🌙"},{id:3,n:"Espacio",e:"🌌"}] },

        // === 3. CUERPO (15 retos) ===
        { p: "Ordena los pasos para crecer", items: [{id:1,n:"Bebé",q:"baby",e:"👶"},{id:2,n:"Niño",q:"child",e:"👦"},{id:3,n:"Adolescente",q:"teenager",e:"🧑"},{id:4,n:"Adulto",q:"adult",e:"👨"}] },
        { p: "Lavado de dientes", items: [{id:1,n:"Pasta",e:"🧴"},{id:2,n:"Cepillar",e:"🪥"},{id:3,n:"Enjuagar",e:"💧"}] },
        { p: "Digestión", items: [{id:1,n:"Boca",e:"👄"},{id:2,n:"Garganta",e:"⬇️"},{id:3,n:"Estómago",e:"🍲"},{id:4,n:"Intestino",e:"🔄"}] },
        { p: "Lavado de manos", items: [{id:1,n:"Agua",e:"💧"},{id:2,n:"Jabón",e:"🧼"},{id:3,n:"Frotar",e:"✋"},{id:4,n:"Secar",e:"🙌"}] },
        { p: "Vestirse", items: [{id:1,n:"Calcetín",e:"🧦"},{id:2,n:"Zapato",e:"👟"},{id:3,n:"Cordones",e:"🔗"}] },
        { p: "Rutina mañana", items: [{id:1,n:"Despertar",e:"🌅"},{id:2,n:"Desayunar",e:"🥣"},{id:3,n:"Cole",e:"🏫"}] },
        { p: "El oído", items: [{id:1,n:"Sonido",e:"📢"},{id:2,n:"Oreja",e:"👂"},{id:3,n:"Cerebro",e:"💡"}] },
        { p: "La vista", items: [{id:1,n:"Luz",e:"💡"},{id:2,n:"Ojo",e:"👁️"},{id:3,n:"Imagen",e:"🖼️"}] },
        { p: "Reflejo: ¡Quema!", items: [{id:1,n:"Fuego",e:"🔥"},{id:2,n:"Sentir",e:"🖐️"},{id:3,n:"Quitar mano",e:"⬆️"}] },
        { p: "Crecimiento de pelo", items: [{id:1,n:"Corto",e:"💇"},{id:2,n:"Largo",e:"👱"},{id:3,n:"Peluquería",e:"✂️"}] },
        { p: "Comer", items: [{id:1,n:"Pelar",e:"🍌"},{id:2,n:"Morder",e:"👄"},{id:3,n:"Tragar",e:"⬇️"}] },
        { p: "Ejercicio", items: [{id:1,n:"Calentar",e:"🤸"},{id:2,n:"Correr",e:"🏃"},{id:3,n:"Descansar",e:"💤"}] },
        { p: "Sangre", items: [{id:1,n:"Corazón",e:"❤️"},{id:2,n:"Cuerpo",e:"🧍"}] },
        { p: "Dormir", items: [{id:1,n:"Cama",e:"🛏️"},{id:2,n:"Cerrar ojos",e:"😴"},{id:3,n:"Soñar",e:"✨"}] },
        { p: "Tamaño: De pequeño a grande", items: [{id:1,n:"Dedo",e:"☝️"},{id:2,n:"Mano",e:"✋"},{id:3,n:"Brazo",e:"💪"},{id:4,n:"Cuerpo",e:"🧍"}] },

        // === 4. NATURALEZA (15 retos) ===
        { p: "El Ciclo del Agua", items: [{id:1,n:"Mar",e:"🌊"},{id:2,n:"Vapor",e:"💨"},{id:3,n:"Nube",e:"☁️"},{id:4,n:"Lluvia",e:"🌧️"}] },
        { p: "Crecimiento Planta", items: [{id:1,n:"Semilla",e:"🌱"},{id:2,n:"Raíz",e:"🌱"},{id:3,n:"Tallo",e:"🌳"},{id:4,n:"Flor",e:"🌻"}] },
        { p: "El ciclo del Roble", items: [{id:1,n:"Bellota",e:"🌰"},{id:2,n:"Brote",e:"🌱"},{id:3,n:"Árbol",e:"🌳"}] },
        { p: "Las Estaciones", items: [{id:1,n:"Primavera",e:"🌸"},{id:2,n:"Verano",e:"☀️"},{id:3,n:"Otoño",e:"🍂"},{id:4,n:"Invierno",e:"❄️"}] },
        { p: "Vida de una flor", items: [{id:1,n:"Capullo",e:"🌱"},{id:2,n:"Abierta",e:"🌸"},{id:3,n:"Seca",e:"🥀"}] },
        { p: "Ciclo del día", items: [{id:1,n:"Alba",e:"🌅"},{id:2,n:"Día",e:"☀️"},{id:3,n:"Ocaso",e:"🌇"},{id:4,n:"Noche",e:"🌃"}] },
        { p: "De la manzana al árbol", items: [{id:1,n:"Flor",e:"🌸"},{id:2,n:"Manzana verde",e:"🍏"},{id:3,n:"Manzana roja",e:"🍎"}] },
        { p: "Lluvia", items: [{id:1,n:"Nube gris",e:"☁️"},{id:2,n:"Gotas",e:"💧"},{id:3,n:"Charco",e:"🌊"}] },
        { p: "Fuerza del viento", items: [{id:1,n:"Brisa",e:"🍃"},{id:2,n:"Viento",e:"💨"},{id:3,n:"Vendaval",e:"🌪️"}] },
        { p: "De madera a mesa", items: [{id:1,n:"Árbol",e:"🌳"},{id:2,n:"Tronco",e:"🪵"},{id:3,n:"Tabla",e:"📏"},{id:4,n:"Mesa",e:"🍽️"}] },
        { p: "Del trigo al pan", items: [{id:1,n:"Trigo",e:"🌾"},{id:2,n:"Harina",e:"🥣"},{id:3,n:"Masa",e:"🥯"},{id:4,n:"Horno",e:"🔥"}] },
        { p: "Ciclo del río", items: [{id:1,n:"Montaña",e:"⛰️"},{id:2,n:"Río",e:"🏞️"},{id:3,n:"Mar",e:"🌊"}] },
        { p: "Tormenta", items: [{id:1,n:"Calor",e:"🥵"},{id:2,n:"Nube negra",e:"🌑"},{id:3,n:"Rayo",e:"⚡"},{id:4,n:"Lluvia",e:"🌧️"}] },
        { p: "Mes lunar", items: [{id:1,n:"Día 1",e:"🌙"},{id:2,n:"Día 15",e:"🌕"},{id:3,n:"Día 30",e:"🌑"}] },
        { p: "Suelo del bosque", items: [{id:1,n:"Hoja cae",e:"🍃"},{id:2,n:"Hoja seca",e:"🍂"},{id:3,n:"Tierra",e:"🌍"}] },

        // === 5. CIUDAD Y OFICIOS (15 retos) ===
        { p: "Enviar una carta", items: [{id:1,n:"Escribir",e:"📝"},{id:2,n:"Sello",e:"📮"},{id:3,n:"Buzón",e:"📫"},{id:4,n:"Cartero",e:"📬"}] },
        { p: "Reciclaje", items: [{id:1,n:"Botella",e:"🍼"},{id:2,n:"Cubo amarillo",e:"🟨"},{id:3,n:"Camión",e:"🚛"},{id:4,n:"Fábrica",e:"🏭"}] },
        { p: "Construir casa", items: [{id:1,n:"Suelo",e:"🧱"},{id:2,n:"Paredes",e:"🏠"},{id:3,n:"Tejado",e:"🏘️"}] },
        { p: "Cocinar", items: [{id:1,n:"Receta",e:"📖"},{id:2,n:"Ingredientes",e:"🍎"},{id:3,n:"Sartén",e:"🍳"},{id:4,n:"Plato",e:"🍽️"}] },
        { p: "Bomberos", items: [{id:1,n:"Alarma",e:"🚨"},{id:2,n:"Camión",e:"🚒"},{id:3,n:"Manguera",e:"🚿"},{id:4,n:"Fuego fuera",e:"✅"}] },
        { p: "Ir al médico", items: [{id:1,n:"Sala espera",e:"🛋️"},{id:2,n:"Consulta",e:"👩‍⚕️"},{id:3,n:"Receta",e:"📝"},{id:4,n:"Curado",e:"😊"}] },
        { p: "Semáforo", items: [{id:1,n:"Rojo",e:"🔴"},{id:2,n:"Amarillo",e:"🟡"},{id:3,n:"Verde",e:"🟢"}] },
        { p: "Viaje en autobús", items: [{id:1,n:"Parada",e:"🚏"},{id:2,n:"Pagar",e:"🎫"},{id:3,n:"Sentarse",e:"🚌"},{id:4,n:"Llegada",e:"🏁"}] },
        { p: "Hacer pan", items: [{id:1,n:"Amasar",e:"🥯"},{id:2,n:"Esperar",e:"⏲️"},{id:3,n:"Hornear",e:"🔥"},{id:4,n:"Vender",e:"💰"}] },
        { p: "Día de cole", items: [{id:1,n:"Entrar",e:"🏫"},{id:2,n:"Clase",e:"📚"},{id:3,n:"Recreo",e:"⚽"},{id:4,n:"Salir",e:"🏠"}] },
        { p: "Policía", items: [{id:1,n:"Aviso",e:"📞"},{id:2,n:"Investigar",e:"🕵️"},{id:3,n:"Ayudar",e:"🤝"}] },
        { p: "Jardinero", items: [{id:1,n:"Cavar",e:"⛏️"},{id:2,n:"Plantar",e:"🌱"},{id:3,n:"Regar",e:"🚿"},{id:4,n:"Cortar",e:"✂️"}] },
        { p: "Comprar", items: [{id:1,n:"Lista",e:"📝"},{id:2,n:"Carrito",e:"🛒"},{id:3,n:"Pagar",e:"💳"},{id:4,n:"Bolsas",e:"🛍️"}] },
        { p: "Pintar cuadro", items: [{id:1,n:"Dibujo",e:"✏️"},{id:2,n:"Pintar",e:"🎨"},{id:3,n:"Secar",e:"🖼️"}] },
        { p: "Biblioteca", items: [{id:1,n:"Buscar",e:"🔍"},{id:2,n:"Leer",e:"📖"},{id:3,n:"Devolver",e:"🔙"}] },

        // === 6. MATERIALES Y ENERGÍA (15 retos) ===
        { p: "Vela", items: [{id:1,n:"Nueva",e:"🕯️"},{id:2,n:"Fuego",e:"🔥"},{id:3,n:"Gasta",e:"💧"},{id:4,n:"Acabada",e:"🕯️"}] },
        { p: "Electricidad", items: [{id:1,n:"Central",e:"🏭"},{id:2,n:"Cables",e:"🔌"},{id:3,n:"Interruptor",e:"🔘"},{id:4,n:"Luz",e:"💡"}] },
        { p: "Hielo derretido", items: [{id:1,n:"Hielo",e:"🧊"},{id:2,n:"Calor",e:"☀️"},{id:3,n:"Agua",e:"💧"},{id:4,n:"Vapor",e:"💨"}] },
        { p: "Magnetismo", items: [{id:1,n:"Acercar",e:"🧲"},{id:2,n:"Atracción",e:"⚙️"},{id:3,n:"Pegado",e:"🔗"}] },
        { p: "Pila", items: [{id:1,n:"Llena",e:"🔋"},{id:2,n:"En uso",e:"🎮"},{id:3,n:"Casi vacía",e:"🪫"},{id:4,n:"Vacía",e:"🚫"}] },
        { p: "De arena a cristal", items: [{id:1,n:"Arena",e:"🏖️"},{id:2,n:"Fuego",e:"🔥"},{id:3,n:"Cristal",e:"🧪"},{id:4,n:"Botella",e:"🍾"}] },
        { p: "Sonido", items: [{id:1,n:"Golpear",e:"🥁"},{id:2,n:"Vibración",e:"〰️"},{id:3,n:"Aire",e:"💨"},{id:4,n:"Oído",e:"👂"}] },
        { p: "De árbol a papel", items: [{id:1,n:"Tronco",e:"🪵"},{id:2,n:"Pasta",e:"🥣"},{id:3,n:"Secar",e:"☀️"},{id:4,n:"Papel",e:"📄"}] },
        { p: "Estados Materia", items: [{id:1,n:"Sólido",e:"📦"},{id:2,n:"Líquido",e:"💧"},{id:3,n:"Gas",e:"☁️"}] },
        { p: "Energía Solar", items: [{id:1,n:"Sol",e:"☀️"},{id:2,n:"Panel",e:"🔋"},{id:3,n:"Batería",e:"🔋"},{id:4,n:"Luz",e:"💡"}] },
        { p: "Cocinar huevo", items: [{id:1,n:"Crudo",e:"🥚"},{id:2,n:"Sartén",e:"🍳"},{id:3,n:"Cocinado",e:"🍳"}] },
        { p: "Lápiz", items: [{id:1,n:"Afilado",e:"✏️"},{id:2,n:"Escribir",e:"📝"},{id:3,n:"Punta rota",e:"❌"},{id:4,n:"Sacapuntas",e:"✏️"}] },
        { p: "Disolver", items: [{id:1,n:"Agua",e:"🥛"},{id:2,n:"Azúcar",e:"🧂"},{id:3,n:"Mover",e:"🥄"},{id:4,n:"Mezcla",e:"💧"}] },
        { p: "Fuerza", items: [{id:1,n:"Empujar",e:"💪"},{id:2,n:"Mover",e:"🏃"},{id:3,n:"Velocidad",e:"⚡"},{id:4,n:"Parar",e:"🛑"}] },
        { p: "Sombra", items: [{id:1,n:"Luz",e:"💡"},{id:2,n:"Objeto",e:"📦"},{id:3,n:"Sombra",e:"👤"}] }
    ],

    // --- 4. VERDADERO O FALSO (Afirmaciones visuales) ---
"vf": [
        // === 1. ANIMALES (15 retos) ===
        { p: "Los leones comen hierba.", q: "lion", e: "🦁", c: false },
        { p: "Los pájaros tienen plumas.", q: "bird", e: "🐦", c: true },
        { p: "Las arañas tienen ocho patas.", q: "spider", e: "🕷️", c: true },
        { p: "Los delfines viven en el bosque.", q: "dolphin", e: "🐬", c: false },
        { p: "Las vacas nos dan leche.", q: "cow", e: "🐄", c: true },
        { p: "Las gallinas vuelan tan alto como los aviones.", q: "hen", e: "🐔", c: false },
        { p: "Las ranas nacen de huevos.", q: "frog", e: "🐸", c: true },
        { p: "Los tiburones tienen huesos de madera.", q: "shark", e: "🦈", c: false },
        { p: "Las hormigas son muy fuertes.", q: "ant", e: "🐜", c: true },
        { p: "Los pingüinos viven en el desierto.", q: "penguin", e: "🐧", c: false },
        { p: "Los conejos comen zanahorias.", q: "rabbit", e: "🐰", c: true },
        { p: "Las serpientes tienen cuatro patas.", q: "snake", e: "🐍", c: false },
        { p: "A los monos les gustan los plátanos.", q: "monkey", e: "🐒", c: true },
        { p: "Los tigres tienen rayas en su piel.", q: "tiger", e: "🐯", c: true },
        { p: "Las ballenas respiran bajo el agua como los peces.", q: "whale", e: "🐳", c: false },

        // === 2. ESPACIO (15 retos) ===
        { p: "El Sol es una estrella.", q: "sun", e: "☀️", c: true },
        { p: "La Luna es un planeta.", q: "moon", e: "🌙", c: false },
        { p: "Marte es de color rojo.", q: "mars", e: "🔴", c: true },
        { p: "Saturno tiene anillos a su alrededor.", q: "saturn", e: "🪐", c: true },
        { p: "Los astronautas comen pizza fresca en la Luna.", q: "astronaut", e: "👩‍🚀", c: false },
        { p: "Las estrellas son pequeños puntos de luz.", q: "stars", e: "✨", c: false },
        { p: "En el espacio hay aire para respirar.", q: "space", e: "🌌", c: false },
        { p: "La Tierra es plana como un plato.", q: "earth", e: "🌍", c: false },
        { p: "Los cohetes sirven para ir al espacio.", q: "rocket", e: "🚀", c: true },
        { p: "El Sol gira alrededor de la Tierra.", q: "solar-system", e: "☀️", c: false },
        { p: "Nosotros vivimos en el planeta Tierra.", q: "earth", e: "🌍", c: true },
        { p: "Los telescopios sirven para ver cosas lejanas.", q: "telescope", e: "🔭", c: true },
        { p: "Júpiter es el planeta más grande.", q: "jupiter", e: "🪐", c: true },
        { p: "Se puede caminar sobre el Sol sin quemarse.", q: "sun", e: "☀️", c: false },
        { p: "El traje espacial protege a los astronautas.", q: "spacesuit", e: "👨‍🚀", c: true },

        // === 3. CUERPO (15 retos) ===
        { p: "Los ojos sirven para escuchar música.", q: "eye", e: "👁️", c: false },
        { p: "El corazón bombea sangre a todo el cuerpo.", q: "heart", e: "❤️", c: true },
        { p: "Los pulmones nos ayudan a respirar.", q: "lungs", e: "🫁", c: true },
        { p: "El estómago guarda la comida que comemos.", q: "stomach", e: "🍲", c: true },
        { p: "La lengua sirve para sentir los sabores.", q: "tongue", e: "👅", c: true },
        { p: "Los huesos de nuestro cuerpo son blandos.", q: "skeleton", e: "🦴", c: false },
        { p: "El cerebro está dentro de la cabeza.", q: "brain", e: "🧠", c: true },
        { p: "Lavar los dientes es malo para la salud.", q: "toothbrush", e: "🪥", c: false },
        { p: "Las orejas nos ayudan a mantener el equilibrio.", q: "ear", e: "👂", c: true },
        { p: "Tenemos uñas en los dedos.", q: "hand", e: "💅", c: true },
        { p: "Tenemos tres piernas.", q: "legs", e: "🦵", c: false },
        { p: "La sangre es de color azul.", q: "blood", e: "🩸", c: false },
        { p: "La piel cubre todo nuestro cuerpo.", q: "skin", e: "✋", c: true },
        { p: "Dormir ayuda a que el cuerpo descanse.", q: "sleep", e: "💤", c: true },
        { p: "La nariz sirve para oler flores.", q: "nose", e: "👃", c: true },

        // === 4. NATURALEZA (15 retos) ===
        { p: "Los árboles nos dan oxígeno para respirar.", q: "tree", e: "🌳", c: true },
        { p: "Las plantas solo necesitan oscuridad para crecer.", q: "plant", e: "🌱", c: false },
        { p: "El arcoíris tiene solo dos colores.", q: "rainbow", e: "🌈", c: false },
        { p: "Los cactus viven en la nieve.", q: "cactus", e: "🌵", c: false },
        { p: "En otoño se caen las hojas de muchos árboles.", q: "autumn", e: "🍂", c: true },
        { p: "En primavera nacen muchas flores.", q: "spring", e: "🌸", c: true },
        { p: "El invierno es la estación más calurosa.", q: "winter", e: "❄️", c: false },
        { p: "La lluvia sale de debajo de la tierra.", q: "rain", e: "🌧️", c: false },
        { p: "El viento es aire en movimiento.", q: "wind", e: "💨", c: true },
        { p: "Las semillas se convierten en plantas.", q: "seed", e: "🌱", c: true },
        { p: "Las nubes están hechas de algodón de azúcar.", q: "cloud", e: "☁️", c: false },
        { p: "Los ríos llevan agua dulce.", q: "river", e: "🏞️", c: true },
        { p: "El rayo se ve antes de que suene el trueno.", q: "lightning", e: "⚡", c: true },
        { p: "Las flores no necesitan el sol.", q: "flower", e: "🌻", c: false },
        { p: "Los volcanes lanzan cubitos de hielo.", q: "volcano", e: "🌋", c: false },

        // === 5. CIUDAD Y OFICIOS (15 retos) ===
        { p: "Los bomberos apagan incendios.", q: "fireman", e: "👨‍🚒", c: true },
        { p: "Los médicos trabajan en las panaderías.", q: "doctor", e: "👩‍⚕️", c: false },
        { p: "El cartero entrega las cartas en las casas.", q: "postman", e: "📬", c: true },
        { p: "Los autobuses pueden volar por las nubes.", q: "bus", e: "🚌", c: false },
        { p: "El semáforo tiene cuatro colores.", q: "traffic-light", e: "🚥", c: false },
        { p: "Los policías ayudan a mantener la seguridad.", q: "police", e: "👮", c: true },
        { p: "Los cocineros preparan comida rica.", q: "cook", e: "👨‍🍳", c: true },
        { p: "Los profesores enseñan en el colegio.", q: "teacher", e: "👩‍🏫", c: true },
        { p: "Los trenes viajan por las vías.", q: "train", e: "🚆", c: true },
        { p: "Los pilotos conducen barcos piratas.", q: "pilot", e: "🧑‍✈️", c: false },
        { p: "En las bibliotecas hay que gritar mucho.", q: "library", e: "📚", c: false },
        { p: "Los camiones de basura limpian la ciudad.", q: "garbage-truck", e: "🚛", c: true },
        { p: "El panadero fabrica pan y pasteles.", q: "baker", e: "👨‍制造", c: true },
        { p: "Los hospitales son para ir a jugar al fútbol.", q: "hospital", e: "🏥", c: false },
        { p: "El metro viaja por debajo de la tierra.", q: "subway", e: "🚇", c: true },

        // === 6. MATERIALES Y ENERGÍA (15 retos) ===
        { p: "El metal es un material muy duro.", q: "metal", e: "⚙️", c: true },
        { p: "Los imanes pueden pegar trozos de madera.", q: "magnet", e: "🧲", c: false },
        { p: "El cristal es transparente y podemos ver a través.", q: "glass", e: "🪟", c: true },
        { p: "El papel se fabrica con madera de los árboles.", q: "paper", e: "📄", c: true },
        { p: "El hielo está muy caliente.", q: "ice", e: "🧊", c: false },
        { p: "La electricidad hace que las lámparas luzcan.", q: "electricity", e: "💡", c: true },
        { p: "Una esponja es un material muy blando.", q: "sponge", e: "🧽", c: true },
        { p: "Una piedra flota en el agua como un barco.", q: "rock", e: "🪨", c: false },
        { p: "La goma es un material flexible.", q: "rubber", e: "➰", c: true },
        { p: "Las pilas guardan energía para los juguetes.", q: "battery", e: "🔋", c: true },
        { p: "La luz viaja muy, muy despacio.", q: "light", e: "🔦", c: false },
        { p: "La lana viene de las ovejas.", q: "wool", e: "🧶", c: true },
        { p: "El plástico es un material natural del bosque.", q: "plastic", e: "🧴", c: false },
        { p: "El fuego da calor.", q: "fire", e: "🔥", c: true },
        { p: "El diamante es el material más duro de todos.", q: "diamond", e: "💎", c: true }
    ],
	

    // --- 5. EL INTRUSO (Uno no encaja) ---
"intruso": [
        // === 1. ANIMALES (15 retos) ===
        { p: "Toca el que NO es un ave", items: [{q:"canary",e:"🐦",i:false},{q:"hen",e:"🐔",i:false},{q:"dog",e:"🐶",i:true},{q:"duck",e:"🦆",i:false}] },
        { p: "Toca el que VIVE en el mar", items: [{q:"shark",e:"🦈",i:true},{q:"cow",e:"🐄",i:false},{q:"lion",e:"🦁",i:false},{q:"horse",e:"🐎",i:false}] },
        { p: "Toca el que NO tiene escamas", items: [{q:"fish",e:"🐟",i:false},{q:"snake",e:"🐍",i:false},{q:"bear",e:"🧸",i:true},{q:"crocodile",e:"🐊",i:false}] },
        { p: "Toca el que NO es un insecto", items: [{q:"bee",e:"🐝",i:false},{q:"ant",e:"🐜",i:false},{q:"butterfly",e:"🦋",i:false},{q:"cat",e:"🐱",i:true}] },
        { p: "Toca el que NO nace de un huevo", items: [{q:"hen",e:"🐔",i:false},{q:"turtle",e:"🐢",i:false},{q:"elephant",e:"🐘",i:true},{q:"duck",e:"🦆",i:false}] },
        { p: "Toca el que NO vive en la granja", items: [{q:"cow",e:"🐄",i:false},{q:"tiger",e:"🐯",i:true},{q:"pig",e:"🐷",i:false},{q:"rooster",e:"🐓",i:false}] },
        { p: "Toca el que NO tiene pelo", items: [{q:"cat",e:"🐱",i:false},{q:"dog",e:"🐶",i:false},{q:"frog",e:"🐸",i:true},{q:"rabbit",e:"🐰",i:false}] },
        { p: "Toca el que NO tiene 4 patas", items: [{q:"dog",e:"🐶",i:false},{q:"cat",e:"🐱",i:false},{q:"bird",e:"🐦",i:true},{q:"cow",e:"🐄",i:false}] },
        { p: "Toca el que NO come carne", items: [{q:"lion",e:"🦁",i:false},{q:"wolf",e:"🐺",i:false},{q:"rabbit",e:"🐰",i:true},{q:"shark",e:"🦈",i:false}] },
        { p: "Toca el que NO es un animal salvaje", items: [{q:"tiger",e:"🐯",i:false},{q:"giraffe",e:"🦒",i:false},{q:"sheep",e:"🐑",i:true},{q:"zebra",e:"🦓",i:false}] },
        { p: "Toca el que NO tiene trompa", items: [{q:"elephant",e:"🐘",i:false},{q:"pig",e:"🐷",i:true},{q:"mammoth",e:"🐘",i:false}] },
        { p: "Toca el que NO es un reptil", items: [{q:"snake",e:"🐍",i:false},{q:"turtle",e:"🐢",i:false},{q:"frog",e:"🐸",i:true},{q:"lizard",e:"🦎",i:false}] },
        { p: "Toca el que NO sabe nadar", items: [{q:"dolphin",e:"🐬",i:false},{q:"whale",e:"🐳",i:false},{q:"monkey",e:"🐒",i:true},{q:"fish",e:"🐟",i:false}] },
        { p: "Toca el que NO puede ser una mascota", items: [{q:"cat",e:"🐱",i:false},{q:"dog",e:"🐶",i:false},{q:"hamster",e:"🐹",i:false},{q:"leopard",e:"🐆",i:true}] },
        { p: "Toca el que NO tiene alas", items: [{q:"bird",e:"🐦",i:false},{q:"butterfly",e:"🦋",i:false},{q:"fish",e:"🐟",i:true},{q:"bee",e:"🐝",i:false}] },

        // === 2. ESPACIO (15 retos) ===
        { p: "Toca el que NO es un planeta", items: [{q:"earth",e:"🌍",i:false},{q:"mars",e:"🔴",i:false},{q:"sun",e:"☀️",i:true},{q:"venus",e:"🟠",i:false}] },
        { p: "Toca el que NO tiene anillos", items: [{q:"saturn",e:"🪐",i:false},{q:"neptune",e:"🔵",i:false},{q:"earth",e:"🌍",i:true},{q:"uranus",e:"💎",i:false}] },
        { p: "Toca el que NO es una estrella", items: [{q:"sun",e:"☀️",i:false},{q:"star",e:"✨",i:false},{q:"moon",e:"🌙",i:true}] },
        { p: "Toca el que NO vuela al espacio", items: [{q:"rocket",e:"🚀",i:false},{q:"airplane",e:"✈️",i:true},{q:"satellite",e:"🛰️",i:false}] },
        { p: "Toca el que NO es un oficio del espacio", items: [{q:"astronaut",e:"👨‍🚀",i:false},{q:"butcher",e:"🥩",i:true},{q:"scientist",e:"👨‍🔬",i:false}] },
        { p: "Toca el que NO es redondo", items: [{q:"sun",e:"☀️",i:false},{q:"moon",e:"🌕",i:false},{q:"rocket",e:"🚀",i:true},{q:"earth",e:"🌍",i:false}] },
        { p: "Toca el que NO brilla con luz propia", items: [{q:"sun",e:"☀️",i:false},{q:"star",e:"✨",i:false},{q:"moon",e:"🌙",i:true}] },
        { p: "Toca el que NO es un transporte espacial", items: [{q:"rocket",e:"🚀",i:false},{q:"ufo",e:"🛸",i:false},{q:"bicycle",e:"🚲",i:true}] },
        { p: "Toca el que NO es frío", items: [{q:"pluto",e:"❄️",i:false},{q:"neptune",e:"🔵",i:false},{q:"sun",e:"☀️",i:true}] },
        { p: "Toca el que NO es una fase de la luna", items: [{q:"full-moon",e:"🌕",i:false},{q:"new-moon",e:"🌑",i:false},{q:"sunny-day",e:"☀️",i:true}] },
        { p: "Toca el que NO es una galaxia", items: [{q:"milky-way",e:"🌌",i:false},{q:"mountain",e:"⛰️",i:true},{q:"universe",e:"✨",i:false}] },
        { p: "Toca el objeto que NO usa el astronauta", items: [{q:"helmet",e:"🪖",i:false},{q:"camera",e:"📷",i:false},{q:"frying-pan",e:"🍳",i:true}] },
        { p: "Toca lo que NO verías con un telescopio", items: [{q:"star",e:"⭐",i:false},{q:"planet",e:"🪐",i:false},{q:"ant",e:"🐜",i:true}] },
        { p: "Toca el planeta que NO es gigante", items: [{q:"jupiter",e:"🪐",i:false},{q:"saturn",e:"🪐",i:false},{q:"earth",e:"🌍",i:true}] },
        { p: "Toca el que NO es un color del espacio", items: [{q:"black",e:"⬛",i:false},{q:"dark-blue",e:"🟦",i:false},{q:"bright-pink",e:"💗",i:true}] },

        // === 3. CUERPO (15 retos) ===
        { p: "Toca lo que NO es un órgano", items: [{q:"heart",e:"❤️",i:false},{q:"lung",e:"🫁",i:false},{q:"shoe",e:"👟",i:true},{q:"brain",e:"🧠",i:false}] },
        { p: "Toca lo que NO es un hueso", items: [{q:"skull",e:"💀",i:false},{q:"spine",e:"🦴",i:false},{q:"muscle",e:"💪",i:true},{q:"human-bone",e:"🦴",i:false}] },
        { p: "Toca lo que NO es un sentido", items: [{q:"eye",e:"👁️",i:false},{q:"ear",e:"👂",i:false},{q:"heart",e:"💖",i:true},{q:"hand",e:"✋",i:false}] },
        { p: "Toca el que NO es saludable", items: [{q:"fruit",e:"🍎",i:false},{q:"water",e:"💧",i:false},{q:"candy",e:"🍬",i:true},{q:"vegetable",e:"🥕",i:false}] },
        { p: "Toca el que NO es una parte de la cara", items: [{q:"nose",e:"👃",i:false},{q:"eye",e:"👁️",i:false},{q:"knee",e:"🦵",i:true},{q:"mouth",e:"👄",i:false}] },
        { p: "Toca lo que NO es interno", items: [{q:"heart",e:"❤️",i:false},{q:"lung",e:"🫁",i:false},{q:"hair",e:"💇",i:true},{q:"brain",e:"🧠",i:false}] },
        { p: "Toca el que NO usamos para comer", items: [{q:"mouth",e:"👄",i:false},{q:"tongue",e:"👅",i:false},{q:"hand",e:"✋",i:false},{q:"ear",e:"👂",i:true}] },
        { p: "Toca el que NO sirve para moverse", items: [{q:"leg",e:"🦵",i:false},{q:"arm",e:"💪",i:false},{q:"chair",e:"🪑",i:true},{q:"foot",e:"🦶",i:false}] },
        { p: "Toca el que NO es un líquido del cuerpo", items: [{q:"blood",e:"🩸",i:false},{q:"saliva",e:"💦",i:false},{q:"bone",e:"🦴",i:true},{q:"tears",e:"💧",i:false}] },
        { p: "Toca lo que NO sirve para la higiene", items: [{q:"soap",e:"🧼",i:false},{q:"toothbrush",e:"🪥",i:false},{q:"chocolate",e:"🍫",i:true},{q:"towel",e:"🛀",i:false}] },
        { p: "Toca lo que NO es para dormir", items: [{q:"bed",e:"🛏️",i:false},{q:"pillow",e:"☁️",i:false},{q:"hammer",e:"🔨",i:true},{q:"pajamas",e:"👕",i:false}] },
        { p: "Toca lo que NO está en la boca", items: [{q:"teeth",e:"🦷",i:false},{q:"tongue",e:"👅",i:false},{q:"eye",e:"👁️",i:true}] },
        { p: "Toca lo que NO usamos para hacer deporte", items: [{q:"sneakers",e:"👟",i:false},{q:"ball",e:"⚽",i:false},{q:"television",e:"📺",i:true}] },
        { p: "Toca lo que NO tenemos por duplicado", items: [{q:"eyes",e:"👀",i:false},{q:"ears",e:"👂",i:false},{q:"nose",e:"👃",i:true},{q:"hands",e:"🙌",i:false}] },
        { p: "Toca lo que NO tenemos por duplicado", items: [{q:"eyes",e:"👀",i:false},{q:"ears",e:"👂",i:false},{q:"nose",e:"👃",i:true},{q:"hands",e:"🙌",i:false}] },
        { p: "Toca el que NO es un médico", items: [{q:"doctor",e:"👨‍⚕️",i:false},{q:"dentist",e:"🦷",i:false},{q:"cook",e:"👨‍🍳",i:true}] },

        // === 4. NATURALEZA (15 retos) ===
        { p: "Toca lo que NO es una planta", items: [{q:"tree",e:"🌳",i:false},{q:"flower",e:"🌸",i:false},{q:"rock",e:"🪨",i:true},{q:"leaf",e:"🍃",i:false}] },
        { p: "Toca lo que NO es clima", items: [{q:"rain",e:"🌧️",i:false},{q:"thunder",e:"🌩️",i:false},{q:"dog",e:"🐶",i:true},{q:"wind",e:"💨",i:false}] },
        { p: "Toca el que NO es un estado del agua", items: [{q:"ice",e:"🧊",i:false},{q:"water-drop-1",e:"💧",i:false},{q:"fire",e:"🔥",i:true},{q:"gas",e:"🌫️",i:false}] },
        { p: "Toca el que NO se ve en verano", items: [{q:"sun",e:"☀️",i:false},{q:"pool",e:"🏊",i:false},{q:"snow",e:"❄️",i:true},{q:"ice-cream",e:"🍦",i:false}] },
        { p: "Toca el que NO es una parte de la planta", items: [{q:"root",e:"🌱",i:false},{q:"stem",e:"🌳",i:false},{q:"hand",e:"✋",i:true},{q:"flower",e:"🌸",i:false}] },
        { p: "Toca lo que NO está en el cielo", items: [{q:"star",e:"⭐",i:false},{q:"cloud",e:"☁️",i:false},{q:"mountain",e:"⛰️",i:true},{q:"sun",e:"☀️",i:false}] },
        { p: "Toca lo que NO es un elemento natural", items: [{q:"rock",e:"🪨",i:false},{q:"river",e:"🌊",i:false},{q:"car",e:"🚗",i:true},{q:"wind",e:"💨",i:false}] },
        { p: "Toca lo que NO necesita agua para vivir", items: [{q:"flower",e:"🌸",i:false},{q:"bird",e:"🐦",i:false},{q:"table",e:"🍽️",i:true},{q:"tree",e:"🌳",i:false}] },
        { p: "Toca el que NO es una estación", items: [{q:"spring",e:"🌸",i:false},{q:"autumn",e:"🍂",i:false},{q:"monday",e:"📅",i:true},{q:"summer",e:"☀️",i:false}] },
        { p: "Toca el que NO es un fenómeno", items: [{q:"rain",e:"🌧️",i:false},{q:"thunder",e:"🌩️",i:false},{q:"tree",e:"🌳",i:true},{q:"wind",e:"💨",i:false}] },
        { p: "Toca el que NO tiene semillas", items: [{q:"apple",e:"🍎",i:false},{q:"watermelon",e:"🍉",i:false},{q:"bread",e:"🍞",i:true},{q:"orange",e:"🍊",i:false}] },
        { p: "Toca el que NO es un color de la naturaleza", items: [{q:"green",e:"🟢",i:false},{q:"blue",e:"🔵",i:false},{q:"neon-pink",e:"💗",i:true},{q:"brown",e:"🟫",i:false}] },
        { p: "Toca lo que NO verías en un bosque", items: [{q:"tree",e:"🌳",i:false},{q:"mushroom",e:"🍄",i:false},{q:"train",e:"🚂",i:true}] },
        { p: "Toca lo que NO es un desastre natural", items: [{q:"flood",e:"🌊",i:false},{q:"storm",e:"⛈️",i:false},{q:"party",e:"🥳",i:true}] },
        { p: "Toca la flor que NO existe", items: [{q:"rose",e:"🌹",i:false},{q:"sunflower",e:"🌻",i:false},{q:"lego-flower",e:"🧱",i:true}] },

        // === 5. CIUDAD Y OFICIOS (15 retos) ===
        { p: "Toca el que NO es un medio de transporte", items: [{q:"car",e:"🚗",i:false},{q:"bus",e:"🚌",i:false},{q:"bicycle",e:"🚲",i:false},{q:"bed",e:"🛏️",i:true}] },
        { p: "Toca el que NO trabaja en un hospital", items: [{id:"doctor",q:"doctor",e:"👨‍⚕️",i:false},{q:"nurse",e:"👩‍⚕️",i:false},{q:"fireman",e:"👨‍🚒",i:true}] },
        { p: "Toca lo que NO hay en una calle", items: [{q:"streetlight",e:"💡",i:false},{q:"sidewalk",e:"🛣️",i:false},{q:"shower",e:"🚿",i:true}] },
        { p: "Toca el que NO usa uniforme", items: [{q:"policeman",e:"👮",i:false},{q:"astronaut",e:"👨‍🚀",i:false},{q:"child",e:"🧒",i:true}] },
        { p: "Toca lo que NO es una tienda", items: [{q:"bakery",e:"🥖",i:false},{q:"hospital",e:"🏥",i:false},{q:"forest",e:"🌳",i:true}] },
        { p: "Toca el que NO trabaja con comida", items: [{q:"cook",e:"👨‍🍳",i:false},{q:"waiter",e:"🤵",i:false},{q:"carpenter",e:"🪚",i:true}] },
        { p: "Toca el transporte que NO va por tierra", items: [{q:"car",e:"🚗",i:false},{q:"train",e:"🚆",i:false},{q:"boat",e:"🚢",i:true}] },
        { p: "Toca lo que NO es dinero", items: [{q:"bill",e:"💵",i:false},{q:"coin",e:"🪙",i:false},{q:"leaf",e:"🍃",i:true}] },
        { p: "Toca lo que NO hay en un colegio", items: [{q:"desk",e:"🪑",i:false},{q:"blackboard",e:"👩‍🏫",i:false},{id:"fridge",q:"fridge",e:"🧊",i:true}] },
        { p: "Toca el que NO construye casas", items: [{q:"bricklayer",e:"👷",i:false},{q:"architect",e:"📐",i:false},{q:"singer-male",e:"🧑🏼‍🎤",i:true}] },
        { p: "Toca el que NO entrega cosas", items: [{q:"postman",e:"📬",i:false},{q:"delivery",e:"📦",i:false},{q:"dentist",e:"🦷",i:true}] },
        { p: "Toca lo que NO verías en un pueblo", items: [{q:"tractor",e:"🚜",i:false},{q:"well",e:"⛲",i:false},{q:"skyscraper",e:"🏢",i:true}] },
        { p: "Toca lo que NO es un edificio público", items: [{q:"library",e:"📚",i:false},{q:"hospital",e:"🏥",i:false},{q:"tent",e:"⛺",i:true}] },
        { p: "Toca el color que NO tiene un semáforo", items: [{q:"red",e:"🔴",i:false},{q:"green",e:"🟢",i:false},{q:"blue",e:"🔵",i:true}] },
        { p: "Toca lo que NO sirve para viajar", items: [{q:"plane",e:"✈️",i:false},{q:"ticket",e:"🎫",i:false},{q:"table",e:"🍽️",i:true}] },

        // === 6. MATERIALES Y ENERGÍA (15 retos) ===
        { p: "Toca el que NO es de metal", items: [{q:"key",e:"🔑",i:false},{q:"spoon",e:"🥄",i:false},{q:"fork",e:"🍴",i:false},{q:"pencil",e:"✏️",i:true}] },
        { p: "Toca el que NO es de madera", items: [{q:"table",e:"🪑",i:false},{q:"pencil",e:"✏️",i:false},{q:"window",e:"🪟",i:true},{q:"stick",e:"🪵",i:false}] },
        { p: "Toca el que NO usa electricidad", items: [{q:"tv",e:"📺",i:false},{q:"lamp",e:"💡",i:false},{q:"fridge",e:"🧊",i:false},{q:"book",e:"📖",i:true}] },
        { p: "Toca el que NO es blando", items: [{q:"pillow",e:"☁️",i:false},{q:"sponge",e:"🧽",i:false},{q:"stone",e:"🪨",i:true},{q:"cotton",e:"☁️",i:false}] },
        { p: "Toca el que NO es transparente", items: [{q:"glass",e:"🪟",i:false},{q:"water",e:"💧",i:false},{q:"wall",e:"🧱",i:true}] },
        { p: "Toca el que NO usa pilas", items: [{q:"remote",e:"🎮",i:false},{q:"flashlight",e:"🔦",i:false},{q:"bicycle",e:"🚲",i:true}] },
        { p: "Toca el que NO es de plástico", items: [{q:"bottle",e:"🧴",i:false},{q:"bag",e:"🛍️",i:false},{q:"coin",e:"🪙",i:true}] },
        { p: "Toca el que NO se dobla (flexible)", items: [{q:"rubber-band",e:"➰",i:false},{q:"paper",e:"📄",i:false},{q:"iron-bar",e:"💪",i:true}] },
        { p: "Toca el que NO flota", items: [{q:"cork",e:"🍾",i:false},{q:"paper-boat",e:"⛵",i:false},{q:"anchor",e:"⚓",i:true}] },
        { p: "Toca el que NO da calor", items: [{q:"fire",e:"🔥",i:false},{q:"sun",e:"☀️",i:false},{q:"ice",e:"🧊",i:true}] },
        { p: "Toca el que NO es de papel", items: [{q:"book",e:"📖",i:false},{q:"newspaper",e:"📰",i:false},{q:"glass-vase",e:"🏺",i:true}] },
        { p: "Toca el que NO es una fuente de luz", items: [{q:"sun",e:"☀️",i:false},{q:"lamp",e:"💡",i:false},{q:"rock",e:"🪨",i:true}] },
        { p: "Toca el que NO es de cristal", items: [{q:"mirror",e:"🪞",i:false},{q:"window",e:"🪟",i:false},{q:"shirt",e:"👕",i:true}] },
        { p: "Toca el que NO es pesado", items: [{q:"elephant",e:"🐘",i:false},{q:"truck",e:"🚛",i:false},{q:"feather",e:"🪶",i:true}] },
        { p: "Toca el que NO es de origen natural", items: [{q:"wood",e:"🪵",i:false},{q:"wool",e:"🧶",i:false},{q:"plastic",e:"🧴",i:true}] }
    ]
};