const GLOSARIO_INSTRUMENTOS = [
	{ n: "El Acordeón", en: "Accordion", f: "acordeon.jpg", s: "" },
	{ n: "La Armónica", en: "Harmonica", f: "armonica.jpg", s: "" },
	{ n: "El Arpa", en: "Harp", f: "arpa.jpg", s: "" },
	{ n: "El Bajo", en: "Bass", f: "bajo.jpg", s: "" },
	{ n: "El Banjo", en: "Banjo", f: "banjo.jpg", s: "" },
	{ n: "La Batería", en: "Drums", f: "bateria.jpg", s: "" },
	{ n: "La Bocina", en: "Motor horn", f: "bocina.jpg", s: "bocina.mp3" },
	{ n: "El Bombo", en: "Bombo", f: "bombo.jpg", s: "" },
	{ n: "Los Bongos", en: "Bongos", f: "bongos.jpg", s: "" },
	{ n: "La Campana", en: "Bell", f: "campana.jpg", s: "" },
	{ n: "Los Cascabeles", en: "Bells", f: "cascabeles.jpg", s: "cascabeles.mp3" },
	{ n: "El Cencerro", en: "Cowbell", f: "cencerro.jpg", s: "cencerro.mp3" },
	{ n: "El Clarinete", en: "Clarinet", f: "clarinete.jpg", s: "" },
	{ n: "El Fagot", en: "Bassoon", f: "fagot.jpg", s: "" },
	{ n: "La Flauta dulce", en: "Recorder", f: "flauta-dulce.jpg", s: "" },
	{ n: "La Flauta travesera", en: "Flute", f: "flauta-travesera.jpg", s: "" },
	{ n: "La Flauta de Pan", en: "Pan Flute", f: "flauta-pan.jpg", s: "" },
	{ n: "La Gaita", en: "Bagpipes", f: "gaita.jpg", s: "" },
	{ n: "El Gong", en: "Gong", f: "gong.jpg", s: "" },
	{ n: "La Guitarra", en: "Spanish Guitar", f: "guitarra-espanola.jpg", s: "" },
	{ n: "La Guitarra Eléctrica", en: "Electric Guitar", f: "guitarra-electrica.jpg", s: "" },
	{ n: "El Güiro", en: "Guiro", f: "guiro.jpg", s: "guiro.mp3" },
	{ n: "El Laúd", en: "Lute", f: "laud.jpg", s: "" },
	{ n: "Las Maracas", en: "Maracas", f: "maracas.jpg", s: "maracas.mp3" },
	{ n: "La Marimba", en: "Marimba", f: "marimba.jpg", s: "" },
	{ n: "La Ocarina", en: "Ocarina", f: "ocarina.jpg", s: "" },
	{ n: "El Órgano", en: "Organ", f: "organo.jpg", s: "" },
	{ n: "Los Palillos", en: "Drumsticks", f: "palillos.jpg", s: "palillos.mp3" },
	{ n: "La Pandereta", en: "Tambourine", f: "pandereta.jpg", s: "" },
	{ n: "El Piano", en: "Piano", f: "piano.jpg", s: "" },
	{ n: "Los Platillos", en: "Cymbals", f: "platillos.jpg", s: "platillos.mp3" },
	{ n: "El Saxofón", en: "Saxophone", f: "saxofon.jpg", s: "" },
	{ n: "El Tambor", en: "Drum", f: "tambor.jpg", s: "" },
	{ n: "Los Timbales", en: "Timpani", f: "timbales.jpg", s: "timbales.mp3" },
	{ n: "El Triángulo", en: "Triangle", f: "triangulo.jpg", s: "" },
	{ n: "El Trombón", en: "Trombone", f: "trombon.jpg", s: "" },
	{ n: "La Trompeta", en: "Trumpet", f: "trompeta.jpg", s: "" },
	{ n: "La Tuba", en: "Tuba", f: "tuba.jpg", s: "" },
	{ n: "El Ukelele", en: "Ukulele", f: "ukelele.jpg", s: "" },
	{ n: "El Violín", en: "Violin", f: "violin.jpg", s: "" },
	{ n: "El Violoncello", en: "Cello", f: "violoncello.jpg", s: "" },
	{ n: "El Xilófono", en: "Xylophone", f: "xilofono.jpg", s: "" }
];